<a href="https://colab.research.google.com/github/yongjaeahn/python_coding/blob/main/korean/source/06_06_%EC%A0%95%EB%A0%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

	정렬

In [ ]:
string_vector = '코딩 123 혹은 ABC'
print("순방향 정렬 :", sorted(string_vector))
print("역방향 정렬 :", sorted(string_vector,reverse=True))

순방향 정렬 : [' ', ' ', ' ', '1', '2', '3', 'A', 'B', 'C', '딩', '은', '코', '혹']
역방향 정렬 : ['혹', '코', '은', '딩', 'C', 'B', 'A', '3', '2', '1', ' ', ' ', ' ']


In [ ]:
string_vector = '코딩 ABC'
string_vector_list = list(string_vector)
print("리스트로 변환한 string_vector :",string_vector_list)
print("형변환을 사용하여 다시 문자열로 변환한 string_vector :",str(string_vector_list))
print("다시 문자열로 변환한 string_vector :",''.join(string_vector_list))

리스트로 변환한 string_vector : ['코', '딩', ' ', 'A', 'B', 'C']
형변환을 사용하여 다시 문자열로 변환한 string_vector : ['코', '딩', ' ', 'A', 'B', 'C']
다시 문자열로 변환한 string_vector : 코딩 ABC


In [ ]:
list_vector = [10,19,8,7,15]
sorted_list_vector = sorted(list_vector)
print("순방향 정렬된 list_vector :", sorted_list_vector)
reverse_sorted_list_vector = sorted(list_vector,reverse=True)
print("역방향 정렬된 list_vector :", reverse_sorted_list_vector)
print("원본 list_vector :",list_vector)

순방향 정렬된 list_vector : [7, 8, 10, 15, 19]
역방향 정렬된 list_vector : [19, 15, 10, 8, 7]
원본 list_vector : [10, 19, 8, 7, 15]


In [ ]:
str_list = ['한글1','ABC38','한글02','ABC5']
sorted_str_list = sorted(str_list)
print("순방향 정렬된 str_list :", sorted_str_list)
reverse_sorted_str_list = sorted(str_list,reverse=True)
print("역방향 정렬된 str_list :", reverse_sorted_str_list)

순방향 정렬된 str_list : ['ABC38', 'ABC5', '한글02', '한글1']
역방향 정렬된 str_list : ['한글1', '한글02', 'ABC5', 'ABC38']


In [ ]:
list_vector = [10,19,8,7,15]
print("순방향 정렬된 list_vector :", list_vector.sort())
print("원본 list_vector :",list_vector)

print("역방향 정렬된 list_vector :", list_vector.sort(reverse=True))
print("원본 list_vector :",list_vector)

순방향 정렬된 list_vector : None
원본 list_vector : [7, 8, 10, 15, 19]
역방향 정렬된 list_vector : None
원본 list_vector : [19, 15, 10, 8, 7]


In [ ]:
import numpy as np

array_vector = np.array([10,19,8,7,15])
print("순방향 정렬된 array_vector :", sorted(array_vector))
print("역방향 정렬된 array_vector :", sorted(array_vector,reverse=True))
print("원본 array_vector :",array_vector)

array_vector = np.array([10,19,8,7,15])
print("array_vector.sort()의 반환값 :", array_vector.sort())
print("원본 array_vector (순방향 정렬된 array_vector) :",array_vector)
print("역방향 정렬된 array_vector :", array_vector.sort(reverse=True))
print("원본 array_vector (역방향 정렬된 array_vector) :",array_vector)

순방향 정렬된 array_vector : [7, 8, 10, 15, 19]
역방향 정렬된 array_vector : [19, 15, 10, 8, 7]
원본 array_vector : [10 19  8  7 15]
array_vector.sort()의 반환값 : None
원본 array_vector (순방향 정렬된 array_vector) : [ 7  8 10 15 19]
원본 array_vector (순방향 정렬된 array_vector) : [ 7  8 10 15 19]


TypeError: ignored

In [ ]:
print(array_vector[::-1])

[19 15 10  8  7]


In [ ]:
import numpy as np

array_matrix = np.array([[9,2,7],[1,7,5],[3,5,3]])
print("array_matrix :\n", array_matrix)
print("열방향 순방향 정렬된 array_matrix :\n", np.sort(array_matrix,axis=0))
print("열방향 역방향 정렬된 array_matrix :\n", np.sort(array_matrix,axis=0)[::-1,:])
print("행방향 순방향 정렬된 array_matrix :\n", np.sort(array_matrix,axis=1))
print("행방향 순방향 정렬된 array_matrix :\n", np.sort(array_matrix,axis=1)[:,::-1])
print("원본 array_matrix :\n", array_matrix)

array_matrix :
 [[9 2 7]
 [1 7 5]
 [3 5 3]]
열방향 순방향 정렬된 array_matrix :
 [[1 2 3]
 [3 5 5]
 [9 7 7]]
열방향 역방향 정렬된 array_matrix :
 [[9 7 7]
 [3 5 5]
 [1 2 3]]
행방향 순방향 정렬된 array_matrix :
 [[2 7 9]
 [1 5 7]
 [3 3 5]]
행방향 순방향 정렬된 array_matrix :
 [[9 7 2]
 [7 5 1]
 [5 3 3]]
원본 array_matrix :
 [[9 2 7]
 [1 7 5]
 [3 5 3]]


In [ ]:
import numpy as np

list_vector = [10,19,8,7,15]
reversed_list_vector = reversed(list_vector)
print("앞뒤가 전도된 list_vector :", reversed_list_vector)
print("원본 list_vector :",list_vector)
list_vector.reverse()
print("앞뒤가 전도된 list_vector :", list_vector)

array_vector = np.array([10,19,8,7,15])
reversed_array_vector = reversed(array_vector)
print("앞뒤가 전도된 array_vector :", reversed_array_vector)
print("원본 array_vector :",array_vector)

앞뒤가 전도된 list_vector : <list_reverseiterator object at 0x7a71b86d56f0>
원본 list_vector : [10, 19, 8, 7, 15]
앞뒤가 전도된 list_vector : [15, 7, 8, 19, 10]
앞뒤가 전도된 array_vector : <reversed object at 0x7a71b86d4550>
원본 array_vector : [10 19  8  7 15]


In [ ]:
list_vector = [10,19,8,7,15]
reversed_list_vector = reversed(list_vector)
print("앞뒤가 전도된 list_vector :", end=' ')
for i in reversed_list_vector:
  print(i,end=' ')
print()
array_vector = np.array([10,19,8,7,15])
reversed_array_vector = reversed(array_vector)
print("앞뒤가 전도된 array_vector :", end=' ')
for i in reversed_array_vector:
  print(i,end=' ')

앞뒤가 전도된 list_vector : 15 7 8 19 10 
앞뒤가 전도된 array_vector : 15 7 8 19 10 

In [ ]:
import numpy as np

array_vector = np.array([10,19,8,7,15])

sort_index = np.argsort(array_vector)
print("array_vector의 Sort Index :",sort_index)
print("순방향 정렬된 array_vector :",array_vector[sort_index])
print("np.argsort()로 정렬후 array_vector :",array_vector)

sort_index = array_vector.argsort()
print("array_vector의 Sort Index :",array_vector[sort_index])
print("array_vector.argsort()로 정렬후 array_vector :",array_vector)

array_vector의 Sort Index : [3 2 0 4 1]
순방향 정렬된 array_vector : [ 7  8 10 15 19]
np.argsort()로 정렬후 array_vector : [10 19  8  7 15]
array_vector의 Sort Index : [ 7  8 10 15 19]
array_vector.argsort()로 정렬후 array_vector : [10 19  8  7 15]


In [ ]:
import numpy as np

# 한행의 데이터 구성 : 학번, 중간고사, 기말고사
list2d = [('002',90,95),('001',100,90),('003',95,100)]
array2d = np.array([(2,90,95),(1,100,90),(3,95,100)])

def sort_key_function(row):
  return row[0]

print('학번 기준 정렬 결과(list):',sorted(list2d,key=sort_key_function))
list2d.sort(reverse=True,key=sort_key_function)
print('학번 기준 정렬 결과(list):',list2d)

print('학번 기준 정렬 결과(array):\n',sorted(array2d,key=sort_key_function))

학번 기준 정렬 결과(list): [('001', 100, 90), ('002', 90, 95), ('003', 95, 100)]
학번 기준 정렬 결과(list): [('003', 95, 100), ('002', 90, 95), ('001', 100, 90)]
학번 기준 정렬 결과(array):
 [array([  1, 100,  90]), array([ 2, 90, 95]), array([  3,  95, 100])]


In [ ]:
import numpy as np

# 한행의 데이터 구성 : 학번, 중간고사, 기말고사
list2d = [('002',90,95),('001',100,90),('003',95,100)]
array2d = np.array([(2,90,95),(1,100,90),(3,95,100)])

def sort_key_function(row):
  #return row[0]         # 학번
  return row[1]          # 중간고사 성적
  #return row[2]         # 기말고사 성적

print('중간고사 기준 정렬 결과(list):',sorted(list2d,key=sort_key_function))
print('중간고사 기준 정렬 결과(array):\n',sorted(array2d,key=sort_key_function))

중간고사 기준 정렬 결과(list): [('002', 90, 95), ('003', 95, 100), ('001', 100, 90)]
중간고사 기준 정렬 결과(array):
 [array([ 2, 90, 95]), array([  3,  95, 100]), array([  1, 100,  90])]


In [ ]:
def sort_key_function(row):
  return row[1] + row[2]         # 성적 합계

print('성적합계 기준 정렬 결과(list):',sorted(list2d,key=sort_key_function))
print('성적합계 기준 정렬 결과(array):\n',sorted(array2d,key=sort_key_function))

성적합계 기준 정렬 결과(list): [('002', 90, 95), ('001', 100, 90), ('003', 95, 100)]
성적합계 기준 정렬 결과(array):
 [array([ 2, 90, 95]), array([  1, 100,  90]), array([  3,  95, 100])]


In [ ]:
#def sort_key_function(row):
#  return row[1] + row[2]         # 성적 합계
sort_key_function = lambda row: row[1] + row[2]

print('성적합계 기준 정렬 결과(list):',sorted(list2d,key=sort_key_function))
print('성적합계 기준 정렬 결과(array):\n',sorted(array2d,key=sort_key_function))

성적합계 기준 정렬 결과(list): [('002', 90, 95), ('001', 100, 90), ('003', 95, 100)]
성적합계 기준 정렬 결과(array):
 [array([ 2, 90, 95]), array([  1, 100,  90]), array([  3,  95, 100])]


In [ ]:
#sort_key_function = lambda row: row[1] + row[2]

print('성적합계 기준 정렬 결과(list):',sorted(list2d,key=lambda row: row[1] + row[2]))
print('성적합계 기준 정렬 결과(array):\n',sorted(array2d,key=lambda row: row[1] + row[2]))

성적합계 기준 정렬 결과(list): [('002', 90, 95), ('001', 100, 90), ('003', 95, 100)]
성적합계 기준 정렬 결과(array):
 [array([ 2, 90, 95]), array([  1, 100,  90]), array([  3,  95, 100])]


In [ ]:
import numpy as np

# 한행의 데이터 구성 : 학번, 중간고사, 기말고사
list2d = [('002',90,95),('001',100,90),('003',95,100)]
array2d = np.array([(2,90,95),(1,100,90),(3,95,100)])

def sort_key_function(row):
  id, midterm_score, final_score = row
  #  return row[1] + row[2]           # 성적 합계
  return midterm_score + final_score  # 성적 합계

print('성적합계  기준 정렬 결과(list):',sorted(list2d,key=sort_key_function))
print('성적합계  기준 정렬 결과(array):\n',sorted(array2d,key=sort_key_function))

성적합계  기준 정렬 결과(list): [('002', 90, 95), ('001', 100, 90), ('003', 95, 100)]
성적합계  기준 정렬 결과(array):
 [array([ 2, 90, 95]), array([  1, 100,  90]), array([  3,  95, 100])]


In [ ]:
packed_tuple = (1,2,3)
_, value2, _ = packed_tuple
print('value2:',value2)
value1, *_ = packed_tuple
print('value1:',value1)
for value in packed_tuple:
  print(value)

value2: 2
value1: 1
1
2
3


In [ ]:
packed_dict = {'a':1,'b':2,'c':3}
_, value2, _ = packed_dict.items()
print('value2:',value2)
value1, *_ = packed_dict.items()
print('value1:',value1)
for key, value in packed_dict.items():
  print('(',key, ',',value,')')

value2: ('b', 2)
value1: ('a', 1)
( a , 1 )
( b , 2 )
( c , 3 )
