<a href="https://colab.research.google.com/github/yongjaeahn/python_coding/blob/main/korean/source/06_03_%EC%88%98%ED%95%99_%EB%A6%AC%EC%8A%A4%ED%8A%B8%EC%99%80_numpy_%EB%B0%B0%EC%97%B4_%EB%8B%A4%EB%A3%A8%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

	리스트와 numpy 배열 다루기

형상 확인

In [ ]:
import numpy as np

list_vector = [1,2,3,4,5]
array_vector = np.arange(1,6)
print("array_vector :", array_vector)

print("len(list_vector) :", len(list_vector))
print("len(array_vector) :", len(array_vector))

arrayVector : [1 2 3 4 5]
len(listVector) : 5
len(arrayVector) : 5


In [ ]:
import numpy as np

list_matrix = [[1,2,3],[4,5,6]]
array_matrix = np.arange(1,7).reshape(2,3)
print("array_matrix :\n", array_matrix)

print("np.ndim(list_matrix) :", np.ndim(list_matrix))
print("np.ndim(array_matrix) :", np.ndim(array_matrix))
print("np.size(list_matrix) :", np.size(list_matrix))
print("np.size(array_matrix) :", np.size(array_matrix))
print("np.shape(list_matrix) :", np.shape(list_matrix))
print("np.shape(array_matrix) :", np.shape(array_matrix))

arrayMatrix2d :
 [[1 2 3]
 [4 5 6]]
np.ndim(listMatrix2d) : 2
np.ndim(arrayMatrix2d) : 2
np.size(listMatrix2d) : 6
np.size(arrayMatrix2d) : 6
np.shape(listMatrix2d) : (2, 3)
np.shape(arrayMatrix2d) : (2, 3)


In [ ]:
import numpy as np

array_matrix = np.arange(1,7).reshape(2,3)
print("array_matrix :\n", array_matrix)

print("array_matrix.ndim :", array_matrix.ndim)
print("array_matrix.size :", array_matrix.size)
print("array_matrix.shape :", array_matrix.shape)
print("array_matrix.shape :", array_matrix.len)

arrayMatrix2d :
 [[1 2 3]
 [4 5 6]]
arrayMatrix2d.ndim : 2
arrayMatrix2d.size : 6
arrayMatrix2d.shape : (2, 3)


AttributeError: ignored

In [ ]:
shape = np.shape(array_matrix)
print("type(shape) :", type(shape))
print("행의 길이 (shape[0]) :", shape[0], ", 열의 길이 (shape[1]) :", shape[1])

row_len, column_len = np.shape(array_matrix)
print("type(row_len) :", type(row_len), "type(column_len) :", type(column_len))
print("행의 길이 (row_len) :", row_len, ", 열의 길이 (column_len) :", column_len)

type(shape) : <class 'tuple'>
행의 길이 (shape[0]) : 2 , 열의 길이 (shape[1]) : 3
type(rowLen) : <class 'int'> type(columnLen) : <class 'int'>
행의 길이 (rowLen) : 2 , 열의 길이 (columnLen) : 3


In [ ]:
import numpy as np

array3d = np.arange(1,25).reshape(2,4,3)
print("array3d :\n", array3d)
print("np.shape(array3d) :", np.shape(array3d))

shape = np.shape(array3d)
print("x축의 길이 :", shape[0], ", y축의 길이 :", shape[1], ", z축의 길이 :", shape[2])

x_len, y_len, z_len = np.shape(array3d)
print("x축의 길이 :", x_len, ", y축의 길이 :", y_len, ", z축의 길이 :", z_len)

arrayMatrix3d :
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
np.shape(arrayMatrix3d) : (2, 4, 3)
x축의 길이 : 2 , y축의 길이 : 4 , z축의 길이 : 3
x축의 길이 : 2 , y축의 길이 : 4 , z축의 길이 : 3


In [ ]:
for length in shape:
  print("길이 :", length)

for i in range(len(shape)):
  print(i+1, "차원 길이 :", shape[i])

길이 : 2
길이 : 4
길이 : 3
1 차원 길이 : 2
2 차원 길이 : 4
3 차원 길이 : 3


In [ ]:
print("enumerate(shape) :", list(enumerate(shape)))

for i, dim in enumerate(shape):
  print(i+1, "차원 길이 :", dim)

enumerate(shape) : [(0, 2), (1, 4), (2, 3)]
1 차원 길이 : 2
2 차원 길이 : 4
3 차원 길이 : 3


In [ ]:
print("3차원 배열 :\n", array3d)
print("하부 2차원 배열 :\n", array3d[0])
print("하부 1차원 배열 :\n", array3d[0][0])

3차원 행렬 :
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
하부 2차원 행렬 :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
하부 1차원 행렬(벡터) :
 [1 2 3]


In [ ]:
print("1차원 길이 :", len(array3d))
print("2차원 길이 :", len(array3d[0]))
print("3차원 길이 :", len(array3d[0][0]))

1차원 길이 : 2
2차원 길이 : 4
3차원 길이 : 3


In [5]:
def return_multiple_values():
  #return (10,20,30)
  return 10,20,30

returned_values = return_multiple_values()
print("함수 반환값 :",returned_values)
print("함수 반환값 :",returned_values[0],returned_values[1],returned_values[2])
print("함수가 반환한 자료형 :",type(returned_values))

returned_value1,returned_value2,returned_value3 = return_multiple_values()
print("함수 반환값 :",returned_value1,returned_value2,returned_value3)

함수 반환값 : (10, 20, 30)
함수 반환값 : 10 20 30
함수가 반환한 자료형 : <class 'tuple'>
함수 반환값 : 10 20 30


In [6]:
returned_value1 = 5
print("returned_value1 :",returned_value1)
returned_values[0] = 5

returned_value1 : 5


TypeError: ignored

In [ ]:
returned_values = (40,50,60)
print("returned_values : ", returned_values)

returnedValues :  (40, 50, 60)


조회

In [ ]:
import numpy as np

list_vector = [1,2,3,4,5,6,7,8,9,10]
array_vector = np.array([1,2,3,4,5,6,7,8,9,10])

print("첫 요소 :", list_vector[0], array_vector[0])
print("마지막 요소 :", list_vector[-1], array_vector[-1])
print("3~7번째 요소 :", list_vector[2:7], array_vector[2:7])
print("1~7번째 요소 :", list_vector[:7], array_vector[:7])
print("7번째~마지막 요소 :", list_vector[6:], array_vector[6:])
print("2~8번째 요소 중 짝수번째 요소 : ", list_vector[1:8:2], array_vector[1:8:2])
print("마지막에서 2~8번째 요소 중 짝수번째 요소 :", list_vector[-2:-9:-2], array_vector[-2:-9:-2])
print("전체 요소 중 홀수번째 요소 :",list_vector[::2], array_vector[::2])

첫 요소 : 1 1
마지막 요소 : 10 10
3~7번째 요소 : [3, 4, 5, 6, 7] [3 4 5 6 7]
1~7번째 요소 : [1, 2, 3, 4, 5, 6, 7] [1 2 3 4 5 6 7]
7번째~마지막 요소 : [7, 8, 9, 10] [ 7  8  9 10]
2~8번째 요소 중 짝수번째 요소 :  [2, 4, 6, 8] [2 4 6 8]
마지막에서 2~8번째 요소 중 짝수번째 요소 : [9, 7, 5, 3] [9 7 5 3]
전체 요소 중 홀수번째 요소 : [1, 3, 5, 7, 9] [1 3 5 7 9]


In [ ]:
print("첫 3개의 요소와 마지막 3개의 요소 : ", array_vector[[0,1,2,-1,-2,-3]])

첫 3개의 요소와 마지막 3개의 요소 :  [ 1  2  3 10  9  8]


In [ ]:
sampleString = "긴 문자열입니다."
print(sampleString[2:5])

문자열


In [ ]:
import numpy as np

list_matrix = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]]
array_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("array_matrix :\n", array_matrix)

print("첫 요소 :", list_matrix[0][0], array_matrix[0][0], array_matrix[0,0])
print("2행 3열 요소 :", list_matrix[1][2], array_matrix[1][2], array_matrix[1,2])
print("마지막 요소 :", list_matrix[-1][-1], array_matrix[-1][-1], array_matrix[-1,-1])

arrayMatrix2d :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
첫 요소 : 1 1 1
2행 3열 요소 : 8 8 8
마지막 요소 : 25 25 25


In [ ]:
print("1행벡터 :", list_matrix[0], array_matrix[0])
print("3행벡터 :", list_matrix[2][:], array_matrix[2][:])
print("2~4행벡터(리스트) :", list_matrix[1:4])
print("2~4행벡터(배열) :\n", array_matrix[1:4,:])

1행벡터 : [1, 2, 3, 4, 5] [1 2 3 4 5]
3행벡터 : [11, 12, 13, 14, 15] [11 12 13 14 15]
2~4행벡터(리스트) : [[6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
2~4행벡터(배열) :
 [[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
print("1열벡터 :", list_matrix[:][0], array_matrix[:][0])
print("3열벡터 :", list_matrix[:][2], array_matrix[:][2])
print("2~4열벡터(리스트) :", list_matrix[:][1:4])
print("2~4열벡터(배열) :\n", array_matrix[:][1:4])

1열벡터 : [1, 2, 3, 4, 5] [1 2 3 4 5]
3열벡터 : [11, 12, 13, 14, 15] [11 12 13 14 15]
2~4열벡터(리스트) : [[6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
2~4열벡터(배열) :
 [[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
print("1열벡터 :", array_matrix[:,0])
print("3열벡터 :", array_matrix[:,2])
print("2~4열벡터(배열) :\n", array_matrix[:,1:4])

1열벡터 : [ 1  6 11 16 21]
3열벡터 : [ 3  8 13 18 23]
2~4열벡터(배열) :
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]


In [ ]:
print("2~3 행 슬라이싱(1:3) + 2~4 열 슬라이싱(1:4) :\n", array_matrix[1:3,1:4])

2~3 행 슬라이싱(1:3) + 2~4 열 슬라이싱(1:4) :
 [[ 7  8  9]
 [12 13 14]]


In [ ]:
print("첫 1개의 요소 : ", array_matrix[0,0])

첫 1개의 요소 :  1


In [ ]:
print("첫 1개와 마지막 1개의 요소 : ", array_matrix[[0,-1],[0,-1]])

첫 1개와 마지막 1개의 요소 :  [ 1 25]


In [ ]:
print("첫 3개의 요소와 마지막 3개의 요소 : ", array_matrix[[0,0,0,-1,-1,-1],[0,1,2,-1,-2,-3]])

첫 3개의 요소와 마지막 3개의 요소 :  [ 1  2  3 25 24 23]


In [ ]:
print("2행과 4행 :\n", array_matrix[[1,3]])

2행과 4행 :
 [[ 6  7  8  9 10]
 [16 17 18 19 20]]


In [ ]:
print("2열과 4열 :\n", array_matrix[:,[1,3]])

2열과 4열 :
 [[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]
 [22 24]]


In [ ]:
print(array_matrix < 10)

[[ True  True  True  True  True]
 [ True  True  True  True False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [ ]:
print(array_matrix[array_matrix < 10])

mask = array_matrix < 10
print(array_matrix[mask])

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
mask = (array_matrix < 10) | (array_matrix > 20)
print(array_matrix[mask])

[ 1  2  3  4  5  6  7  8  9 21 22 23 24 25]


In [ ]:
import numpy as np

subjects = np.array(["학번","국어","영어","수학","사탐","과탐"])
scores = np.array([[1,90,80,95,100,95],[2,100,80,85,90,95],[3,95,100,80,85,90],[4,80,95,100,90,85],[5,85,80,90,100,95]])
print("성적 :\n", scores)

mask_column = (subjects == "학번") | (subjects == "수학") | (subjects == "과탐")
print(scores[:,mask_column])

성적 :
 [[  1  90  80  95 100  95]
 [  2 100  80  85  90  95]
 [  3  95 100  80  85  90]
 [  4  80  95 100  90  85]
 [  5  85  80  90 100  95]]
[[  1  95  95]
 [  2  85  95]
 [  3  80  90]
 [  4 100  85]
 [  5  90  95]]


In [ ]:
mask_row = scores[:,4] == 100
print(mask_row)
print(scores[mask_row])

[ True False False False  True]
[[  1  90  80  95 100  95]
 [  5  85  80  90 100  95]]


In [ ]:
import numpy as np

employee_list = [320811, "안용제", "010-1234-5678", "서울시 영등포구 당산동", 99.5]
print("리스트(list) : ", employee_list)

employee_array = np.array([320811, "안용제", "010-1234-5678", "서울시 영등포구 당산동", 99.5])
print("배열(array) : ", employee_array)

리스트(list) :  [320811, '안용제', '010-1234-5678', '서울시 영등포구 당산동', 99.5]
배열(array) :  ['320811' '안용제' '010-1234-5678' '서울시 영등포구 당산동' '99.5']


In [ ]:
print("리스트의 성적 - 10 : ", employee_list[4] - 10)

print("배열의 성적 - 10 : ", employee_array[4] - 10)

리스트의 성적 - 10 :  89.5


TypeError: ignored

수정

In [ ]:
list_matrix = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]]

print("list_matrix (수정전):\n", list_matrix)
list_matrix[0][0] = -999
print("list_matrix (수정후):\n", list_matrix)

listMatrix2d (수정전):
 [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]
listMatrix2d (수정후):
 [[-999, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]


In [ ]:
import numpy as np

array_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])

print("array_matrix (수정전) :\n", array_matrix)
array_matrix[1][2] = -888
array_matrix[-1,-1] = -777
print("array_matrix (수정후):\n", array_matrix)

arrayMatrix2d (수정전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (수정후):
 [[   1    2    3    4    5]
 [   6    7 -888    9   10]
 [  11   12   13   14   15]
 [  16   17   18   19   20]
 [  21   22   23   24 -777]]


In [ ]:
array_matrix[0] = 1
array_matrix[2:3,:] = -1
print("array_matrix (수정후):\n", array_matrix)

arrayMatrix2d (수정후):
 [[ 1  1  1  1  1]
 [ 6  7  8  9 10]
 [-1 -1 -1 -1 -1]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
array_matrix[:,0] = 2
array_matrix[:,2:3] = -2
print("array_matrix (수정후):\n", array_matrix)

arrayMatrix2d (수정후):
 [[ 2  1 -2  1  1]
 [ 2  7 -2  9 10]
 [ 2 -1 -2 -1 -1]
 [ 2 17 -2 19 20]
 [ 2 22 -2 24 25]]


In [ ]:
array_matrix[1:3,1:4] = 100
print("array_matrix (수정후):\n", array_matrix)

arrayMatrix2d (수정후):
 [[  2   1  -2   1   1]
 [  2 100 100 100  10]
 [  2 100 100 100  -1]
 [  2  17  -2  19  20]
 [  2  22  -2  24  25]]


In [ ]:
 array_matrix[[0,0,0,-1,-1,-1],[0,1,2,-1,-2,-3]] = -100
 print("array_matrix (수정후):\n", array_matrix)

arrayMatrix2d (수정후):
 [[-100 -100 -100    1    1]
 [   2  100  100  100   10]
 [   2  100  100  100   -1]
 [   2   17   -2   19   20]
 [   2   22 -100 -100 -100]]


In [ ]:
mask = array_matrix == -100
array_matrix[mask] = 100
print("array_matrix (수정후):\n", array_matrix)

arrayMatrix2d (수정후):
 [[100 100 100   1   1]
 [  2 100 100 100  10]
 [  2 100 100 100  -1]
 [  2  17  -2  19  20]
 [  2  22 100 100 100]]


삭제

In [ ]:
list_vector = [1,2,3,4,5,6,7,8,9,10]
print("list_vector (삭제전): ", list_vector)
del list_vector[3]     # 인덱스로 삭제
print("list_vector (인덱스 3 즉 4번째 요소 삭제후): ", list_vector)
list_vector.remove(10) #  값으로 삭제
print("list_vector (값 10으로 삭제후): ", list_vector)

listVector (삭제전):  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
listVector (인덱스 3 즉 4번째 요소 삭제후):  [1, 2, 3, 5, 6, 7, 8, 9, 10]
listVector (값 10으로 삭제후):  [1, 2, 3, 5, 6, 7, 8, 9]


In [ ]:
import numpy as np

array_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("array_matrix (삭제전) :\n", array_matrix)

array_matrix = np.delete(array_matrix,1,axis=0)
print("array_matrix (인덱스 1 즉 2행 삭제후) :\n", array_matrix)
array_matrix = np.delete(array_matrix,-1,axis=1)
print("array_matrix (인덱스 -1 즉 마지막열 삭제후) :\n", array_matrix)
array_matrix = np.delete(array_matrix,[1,3],axis=0)
print("array_matrix (인덱스 1과 3 즉 2행과 4행 삭제후) :\n", array_matrix)

arrayMatrix2d (삭제전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (인덱스 1 즉 2행 삭제후) :
 [[ 1  2  3  4  5]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (인덱스 -1 즉 마지막열 삭제후) :
 [[ 1  2  3  4]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]
arrayMatrix2d (인덱스 1과 3 즉 2행과 4행 삭제후) :
 [[ 1  2  3  4]
 [16 17 18 19]]


추가

In [ ]:
list_vector = [1,2,4,5]
print("list_vector (추가전): ", list_vector)
list_vector.append(6)              # 리스트의 맨뒤에 값을 추가
print("list_vector (6을 추가한 후): ", list_vector)
list_vector.insert(2,3)            # 리스트의 3번째 요소로 3을 추가
print("list_vector (3을 추가한 후): ", list_vector)
list_vector.extend([7,8])          # 리스트의 맨뒤에 7과 8을 리스트로 확장
print("list_vector (7과 8의 리스트를 확장한 후): ", list_vector)
list_vector = [-1,0] + list_vector + [9,10]  # -1,0의 리스트와 9,10의 리스트를 앞뒤로 이어붙임
print("list_vector (-1,0 리스트와 9~10 리스트를 이어붙인 후): ", list_vector)

listVector (추가전):  [1, 2, 4, 5]
listVector (6을 추가한 후):  [1, 2, 4, 5, 6]
listVector (3을 추가한 후):  [1, 2, 3, 4, 5, 6]
listVector (7과 8의 리스트를 확장한 후):  [1, 2, 3, 4, 5, 6, 7, 8]
listVector (-1,0 리스트와 9~10 리스트를 이어붙인 후):  [-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
import numpy as np

array_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("array_matrix (추가전) :\n", array_matrix)
new_row_2d = np.array([[26,27,28,29,30],[31,32,33,34,35]])
print("new_row_2d :\n", new_row_2d)
array_matrix = np.append(array_matrix,new_row_2d,axis=0)
print("array_matrix (신규행 추가후) :\n", array_matrix)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
newRow2d :
 [[26 27 28 29 30]
 [31 32 33 34 35]]
arrayMatrix2d (신규행 추가후) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [ ]:
import numpy as np

array_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("array_matrix (추가전) :\n", array_matrix)
new_row = np.array([26,27,28,29,30])
print("new_row :\n", new_row)
array_matrix = np.append(array_matrix,[new_row],axis=0)
print("array_matrix (신규행 추가후) :\n", array_matrix)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
newRow2d :
 [26 27 28 29 30]
arrayMatrix2d (신규행 추가후) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [ ]:
import numpy as np

array_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("array_matrix (추가전) :\n", array_matrix)
new_rows = np.array([26,27,28,29,30],[31,32,33,34,35])
print("new_rows :\n", new_rows)
array_matrix = np.append(array_matrix,[new_rows],axis=0)
print("array_matrix (신규행 추가후) :\n", array_matrix)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


TypeError: ignored

In [ ]:
import numpy as np

array_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("array_matrix (추가전) :\n", array_matrix)
new_row_2d = np.array([[26,27,28,29,30],[31,32,33,34,35]])
print("new_row_2d :\n", new_row_2d)
array_matrix = np.append(array_matrix,[new_row_2d],axis=0)
print("array_matrix (신규행 추가후) :\n", array_matrix)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
newRow2d :
 [[26 27 28 29 30]
 [31 32 33 34 35]]


ValueError: ignored

In [ ]:
import numpy as np

array_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("array_matrix (추가전) :\n", array_matrix)
new_row_2d = np.array([[26,27,28,29,30]])
print("new_row_2d :\n", new_row_2d)
array_matrix = np.append(array_matrix,new_row_2d,axis=0)
print("array_matrix (신규행 추가후) :\n", array_matrix)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
newRow2d :
 [[26 27 28 29 30]]
arrayMatrix2d (신규행 추가후) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [ ]:
import numpy as np

array_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("array_matrix (추가전) :\n", array_matrix)
new_column_2d = np.array([[26],[27],[28],[29],[30]])
print("new_column_2d :\n", new_column_2d)
array_matrix = np.append(array_matrix,new_column_2d,axis=1)
print("array_matrix (신규열 추가후) :\n", array_matrix)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
newColumn2d :
 [[26]
 [27]
 [28]
 [29]
 [30]]
arrayMatrix2d (신규열 추가후) :
 [[ 1  2  3  4  5 26]
 [ 6  7  8  9 10 27]
 [11 12 13 14 15 28]
 [16 17 18 19 20 29]
 [21 22 23 24 25 30]]


In [ ]:
import numpy as np

array_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("array_matrix (추가전) :\n", array_matrix)
new_row_2d = np.array([[26,27,28,29,30],[31,32,33,34,35]])
print("new_row_2d :\n", new_row_2d)
new_column_2d = np.transpose(new_row_2d)
print("new_column_2d :\n", new_column_2d)
array_matrix = np.append(array_matrix,new_column_2d,axis=1)
print("array_matrix (신규열 추가후) :\n", array_matrix)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
newRow2d :
 [[26 27 28 29 30]
 [31 32 33 34 35]]
newColumn2d :
 [[26 31]
 [27 32]
 [28 33]
 [29 34]
 [30 35]]
arrayMatrix2d (신규열 추가후) :
 [[ 1  2  3  4  5 26 31]
 [ 6  7  8  9 10 27 32]
 [11 12 13 14 15 28 33]
 [16 17 18 19 20 29 34]
 [21 22 23 24 25 30 35]]


In [ ]:
import numpy as np

array_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])

new_row_2d01 = np.array([[26,27,28,29,30]])
new_row_2d02 = np.array([[31,32,33,34,35],[36,37,38,39,40]])
array_matrix = np.concatenate([array_matrix,new_row_2d01,new_row_2d02],axis= 0)
array_matrix = np.vstack((array_matrix,new_row_2d01,new_row_2d02))

array_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])

new_column_2d01 = np.transpose(new_row_2d01)
new_column_2d02 = np.transpose(new_row_2d02)
array_matrix = np.concatenate([array_matrix,new_column_2d01,new_column_2d02],axis= 1)
array_matrix = np.hstack((array_matrix,new_column_2d01,new_column_2d02))

In [ ]:
import numpy as np

array_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("array_matrix (추가전) :\n", array_matrix)

new_row_2d = np.array([[26,27,28,29,30],[31,32,33,34,35]])
array_matrix = np.insert(array_matrix,1,new_row_2d,axis=0)
print("array_matrix (2행으로 신규행 추가후) :\n", array_matrix)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (2행으로 신규행 추가후) :
 [[ 1  2  3  4  5]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
import numpy as np

array_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("array_matrix (추가전) :\n", array_matrix)

new_row_2d = np.array([[26,27,28,29,30],[31,32,33,34,35]])
new_column_2d = np.transpose(new_row_2d)
array_matrix = np.insert(array_matrix,1,new_column_2d,axis=1)
print("array_matrix (2열로 신규열 추가후) :\n", array_matrix)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


ValueError: ignored

In [ ]:
import numpy as np

array_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("array_matrix (추가전) :\n", array_matrix)

new_row_2d = np.array([[26,27,28,29,30],[31,32,33,34,35]])
new_column_2d = np.transpose(new_row_2d)
array_matrix = np.insert(array_matrix,[1,2],new_column_2d,axis=1)
print("array_matrix (2열과 3열로 신규열 추가후) :\n", array_matrix)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (2열과 3열로 신규열 추가후) :
 [[ 1 26  2 31  3  4  5]
 [ 6 27  7 32  8  9 10]
 [11 28 12 33 13 14 15]
 [16 29 17 34 18 19 20]
 [21 30 22 35 23 24 25]]


In [ ]:
import numpy as np

array_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("array_matrix (추가전) :\n", array_matrix)

new_row_2d = np.array([[26,27,28,29,30],[31,32,33,34,35]])
new_column_2d = np.transpose(new_row_2d)
array_matrix = np.insert(array_matrix,[1,1],new_column_2d,axis=1)
print("array_matrix (2열로 신규열 추가후) :\n", array_matrix)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (2열로 신규열 추가후) :
 [[ 1 26 31  2  3  4  5]
 [ 6 27 32  7  8  9 10]
 [11 28 33 12 13 14 15]
 [16 29 34 17 18 19 20]
 [21 30 35 22 23 24 25]]


In [ ]:
import numpy as np

array_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("array_matrix (추가전) :\n", array_matrix)

new_row_2d = np.array([[26,27,28,29,30]])
new_column_2d = np.transpose(new_row_2d)

array_matrix = np.insert(array_matrix,[0,2,3],new_column_2d01,axis=1)
print("array_matrix (1열과 3열과 4열에 신규열 추가후) :\n", array_matrix)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (1열과 3열과 4열에 신규열 추가후) :
 [[26  1  2 26  3 26  4  5]
 [27  6  7 27  8 27  9 10]
 [28 11 12 28 13 28 14 15]
 [29 16 17 29 18 29 19 20]
 [30 21 22 30 23 30 24 25]]


In [ ]:
import numpy as np

array_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("array_matrix (추가전) :\n", array_matrix)

new_row_2d = np.array([[26,27,28,29,30],[31,32,33,34,35]])
array_matrix = np.insert(array_matrix,[1,3],new_row_2d,axis=0)
print("array_matrix (2행과 4행으로 신규행 추가후) :\n", array_matrix)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (2행과 4행으로 신규행 추가후) :
 [[ 1  2  3  4  5]
 [26 27 28 29 30]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [31 32 33 34 35]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
list_vector = []
print("list_vector (빈 벡터) :\n", list_vector)

list_vector.append(1)        # 벡터의 요소값들을 외부에서 읽어 온다고 가정
list_vector.append(2)
list_vector.append(3)
print("list_vector (값을 읽어와 생성한 벡터) :\n", list_vector)

listVector (빈 벡터) :
 []
listVector (값을 읽어와 생성한 벡터) :
 [1, 2, 3]


In [ ]:
import numpy as np

# 행렬의 크기를 외부에서 읽어 온다고 가정
row = 2
column = 3

array_matrix = np.empty(shape=(row, column))
print("array_matrix (빈 배열) :\n", array_matrix)

# 행렬의 요소값들을 외부에서 읽어 온다고 가정
for i in range(row):
  array_matrix[i] = np.array(np.arange(i * column,i * column + column))

print("array_matrix (값을 읽어와 생성한 배열) :\n", array_matrix)

arrayMatrix2d (빈 배열) :
 [[2.5013579e-316 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]]
arrayMatrix2d (값을 읽어와 생성한 배열) :
 [[0. 1. 2.]
 [3. 4. 5.]]


numpy 기타

In [ ]:
import numpy as np

array_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("array_matrix (변경전) :\n", array_matrix)
array_matrix = np.flipud(array_matrix)
print("array_matrix (행렬의 상하 변경후) :\n", array_matrix)

arrayMatrix2d (변경전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (행렬의 상하 변경후) :
 [[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [ ]:
import numpy as np

array_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("array_matrix (변경전) :\n", array_matrix)
array_matrix = np.fliplr(array_matrix)
print("array_matrix (행렬의 좌우 변경후) :\n", array_matrix)

arrayMatrix2d (변경전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (행렬의 좌우 변경후) :
 [[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]


In [ ]:
import numpy as np

array_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("array_matrix (변경전) :\n", array_matrix)
array_matrix = np.flip(array_matrix)
print("array_matrix (행렬의 앞뒤 변경후) :\n", array_matrix)

arrayMatrix2d (변경전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (행렬의 앞뒤 변경후) :
 [[25 24 23 22 21]
 [20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [ ]:
import numpy as np

arrayMatrix3d = np.arange(1,28).reshape(3,3,3)
print("arrayMatrix3d (변경전) :\n", arrayMatrix3d)
arrayMatrix3d = np.flip(arrayMatrix3d,axis=2)
print("arrayMatrix3d (3차원 행렬의 3번째 축 기준 앞뒤 변경후) :\n", arrayMatrix3d)

arrayMatrix3d (변경전) :
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
arrayMatrix3d (3차원 행렬의 3번째 축 기준 앞뒤 변경후) :
 [[[ 3  2  1]
  [ 6  5  4]
  [ 9  8  7]]

 [[12 11 10]
  [15 14 13]
  [18 17 16]]

 [[21 20 19]
  [24 23 22]
  [27 26 25]]]


In [ ]:
import numpy as np

arrayMatrix3d = np.arange(1,28).reshape(3,3,3)
print("arrayMatrix3d (변경전) :\n", arrayMatrix3d)
arrayMatrix3d = np.flip(arrayMatrix3d,axis=(0,2))
print("arrayMatrix3d (3차원 행렬의 1,3번째 축 기준 앞뒤 변경후) :\n", arrayMatrix3d)

arrayMatrix3d (변경전) :
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
arrayMatrix3d (3차원 행렬의 1,3번째 축 기준 앞뒤 변경후) :
 [[[21 20 19]
  [24 23 22]
  [27 26 25]]

 [[12 11 10]
  [15 14 13]
  [18 17 16]]

 [[ 3  2  1]
  [ 6  5  4]
  [ 9  8  7]]]


In [ ]:
import numpy as np

array_matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("array_matrix (변경전) :\n", array_matrix)
array_matrix = np.roll(array_matrix,shift=3)
print("array_matrix (행렬의 앞뒤 변경후) :\n", array_matrix)

arrayMatrix2d (변경전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (행렬의 앞뒤 변경후) :
 [[23 24 25  1  2]
 [ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]]


In [ ]:
import numpy as np

array_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("array_matrix (회전전) :\n", array_matrix)
array_matrix = np.rot90(array_matrix,k=1)
print("array_matrix (시계 반대방향 90도 회전후) :\n", array_matrix)
array_matrix = np.rot90(array_matrix,k=-2)
print("array_matrix (시계 방향 180도 회전후) :\n", array_matrix)

arrayMatrix2d (회전전) :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arrayMatrix2d (시계 반대방향 90도 회전후) :
 [[3 6 9]
 [2 5 8]
 [1 4 7]]
arrayMatrix2d (시계 방향 180도 회전후) :
 [[7 4 1]
 [8 5 2]
 [9 6 3]]


In [ ]:
import numpy as np

arrayMatrix3d = np.arange(1,28).reshape(3,3,3)
print("arrayMatrix3d (회전전) :\n", arrayMatrix3d)
arrayMatrix3d = np.rot90(arrayMatrix3d,k=1,axes=(0,1))
print("arrayMatrix3d (3차원 행렬의 1,2번째 축 기준 90도 회전후) :\n", arrayMatrix3d)

arrayMatrix3d (회전전) :
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
arrayMatrix3d (3차원 행렬의 1,2번째 축 기준 90도 회전후) :
 [[[ 7  8  9]
  [16 17 18]
  [25 26 27]]

 [[ 4  5  6]
  [13 14 15]
  [22 23 24]]

 [[ 1  2  3]
  [10 11 12]
  [19 20 21]]]


In [ ]:
import numpy as np

array_matrix = np.array([[1,2],[3,4]])
print("array_matrix (반복전) :\n", array_matrix)
array_matrix = np.tile(array_matrix, reps=3)
print("array_matrix (3열로 반복후) :\n", array_matrix)

array_matrix = np.array([[1,2],[3,4]])
array_matrix = np.tile(array_matrix, reps=(2,3))
print("array_matrix (2행 3열로 반복후) :\n", array_matrix)

arrayMatrix2d (반복전) :
 [[1 2]
 [3 4]]
arrayMatrix2d (3열로 반복후) :
 [[1 2 1 2 1 2]
 [3 4 3 4 3 4]]
arrayMatrix2d (2행 3열로 반복후) :
 [[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [ ]:
import numpy as np

array_vector = np.arange(10)
print("array_vector (섞기전) :\n", array_vector)
np.random.shuffle(array_vector)
print("array_vector (섞은후) :\n", array_vector)

arrayVector (섞기전) :
 [0 1 2 3 4 5 6 7 8 9]
arrayVector (섞은후) :
 [3 8 0 4 1 2 7 5 9 6]


In [ ]:
import random

list_vector = [0,1,2,3,4,5,6,7,8,9]
print("list_vector (섞기전) :\n", list_vector)
random.shuffle(list_vector)
print("list_vector (섞은후) :\n", list_vector)

listVector (섞기전) :
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
listVector (섞은후) :
 [5, 0, 2, 1, 9, 6, 4, 3, 7, 8]


In [ ]:
import numpy as np

array_matrix = np.arange(1,37).reshape(6,6)
print("array_matrix :\n", array_matrix)

splited_matrix = np.split(array_matrix, 2, axis=0)
print("splited_matrix[0] :\n", splited_matrix[0])
print("splited_matrix[1] :\n", splited_matrix[1])

arrayMatrix2d :
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
splitedMatrix2d[0] :
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
splitedMatrix2d[1] :
 [[19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [ ]:
splited_matrix = np.split(array_matrix, (1,3), axis=0)
print("splited_matrix[0] :\n", splited_matrix[0])
print("splited_matrix[1] :\n", splited_matrix[1])
print("splited_matrix[2] :\n", splited_matrix[2])

splitedMatrix2d[0] :
 [[1 2 3 4 5 6]]
splitedMatrix2d[1] :
 [[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
splitedMatrix2d[2] :
 [[19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [ ]:
import numpy as np

array_vector = np.array([1,2,3,4,5])
array_matrix = np.array([[-2,-1,0,1,2],[1,2,3,4,5]])

print(np.any(array_vector < 0))        # 0보다 작은 값이 있는지 확인
print(np.any(array_matrix < 0))

# 두 배열의 요소가 같은 값이 하나라도 있는지 확인
equal_boolean_idx = np.array([1,2,3]) == np.array([-1,2,-3])
print("equal_boolean_idx :\n",equal_boolean_idx)
np.any(equal_boolean_idx)

False
True
equalBooleanIndex :
 [False  True False]


True

In [ ]:
import numpy as np

array_vector = np.array([1,0,0,0,0])
array_matrix = np.zeros(shape=(2,3))
print("array_matrix : \n", array_matrix)

print(np.all(array_vector == 0))        # 모든 값이 0과 같은지 확인
print(np.all(array_matrix == 0))

# 두 배열의 요소가 모두 같은 값인지 확인
equal_boolean_idx = np.array([1,2,3]) == np.array([-1,2,-3])
print("equal_boolean_idx :\n",equal_boolean_idx)
np.all(equal_boolean_idx)

arrayMatrix2d : 
 [[0. 0. 0.]
 [0. 0. 0.]]
False
True
equalBooleanIndex :
 [False  True False]


False

In [ ]:
import numpy as np

array_matrix01 = np.array([[-2,-1,0,1,2],[1,2,3,4,5]])
array_matrix02 = np.array([[1,0,0,0,1],[5,4,3,2,1]])
array_matrix03 = array_matrix01 / array_matrix02
print("나누어진 행렬 : \n", array_matrix03)

# Not a Number(nan)가 있는지 불리언 인덱스로 확인
isnan_boolean_idx = np.isnan(array_matrix03)
print("isnan_boolean_idx : \n", isnan_boolean_idx)
print("nan이 없는 값만 발췌 : \n", array_matrix03[~isnan_boolean_idx])

나누어진 행렬 : 
 [[-2.  -inf  nan  inf  2. ]
 [ 0.2  0.5  1.   2.   5. ]]
isnanBooleanIndex : 
 [[False False  True False False]
 [False False False False False]]
nan이 없는 값만 발췌 : 
 [-2.  -inf  inf  2.   0.2  0.5  1.   2.   5. ]


<ipython-input-44-666ee8f2a428>:5: RuntimeWarning: divide by zero encountered in true_divide
  arrayMatrix2d03 = arrayMatrix2d01 / arrayMatrix2d02
<ipython-input-44-666ee8f2a428>:5: RuntimeWarning: invalid value encountered in true_divide
  arrayMatrix2d03 = arrayMatrix2d01 / arrayMatrix2d02


In [ ]:
# 무한대(inf,-inf)나 Not a Number(nan)가 없는지 불리언 인덱스로 확인
isfinite_boolean_idx = np.isfinite(array_matrix03)
print("isfinite_boolean_idx : \n", isfinite_boolean_idx)
print("유한한 값만 발췌 : \n", array_matrix03[isfinite_boolean_idx])

isfiniteBooleanIndex : 
 [[ True False False False  True]
 [ True  True  True  True  True]]
유한한 값만 발췌 : 
 [-2.   2.   0.2  0.5  1.   2.   5. ]


In [ ]:
print("nan이 포함되지 않은 배열 비교\n",array_matrix02 == array_matrix02)
print("nan이 포함되지 않은 배열 비교\n",np.array_equal(array_matrix02,array_matrix02))

print("nan이 포함된 배열 비교\n",array_matrix03 == array_matrix03)
print("nan이 포함된 배열 비교\n",np.array_equal(array_matrix03,array_matrix03))

nan이 포함되지 않은 배열 비교
 [[ True  True  True  True  True]
 [ True  True  True  True  True]]
nan이 포함되지 않은 배열 비교
 True
nan이 포함된 배열 비교
 [[ True  True False  True  True]
 [ True  True  True  True  True]]
nan이 포함된 배열 비교
 False


In [ ]:
print("nan인 값을 0으로 바꾼 행렬 :\n",np.where(np.isnan(array_matrix03), 0, array_matrix03))
print("유한하지 않은 값을 0으로 바꾼 행렬 :\n",np.where(~np.isfinite(array_matrix03), 0, array_matrix03))

nan인 값을 0으로 바꾼 행렬 :
 [[-2.  -inf  0.   inf  2. ]
 [ 0.2  0.5  1.   2.   5. ]]
유한하지 않은 값을 0으로 바꾼 행렬 :
 [[-2.   0.   0.   0.   2. ]
 [ 0.2  0.5  1.   2.   5. ]]


In [ ]:
print("0보다 작은 값의 불리언 인덱스 : \n", array_matrix03 < 0)
print("0보다 작은 값 : \n", array_matrix03[array_matrix03 < 0])

print("0보다 작은 값의 인덱스 :\n",np.where(array_matrix03 < 0))
print("0보다 작은 값 :\n", array_matrix03[np.where(array_matrix03 < 0)])

0보다 작은 값의 불리언 인덱스 : 
 [[ True  True False False False]
 [False False False False False]]
0보다 작은 값 : 
 [ -2. -inf]
0보다 작은 값의 인덱스 :
 (array([0, 0]), array([0, 1]))
0보다 작은 값 :
 [ -2. -inf]
