<a href="https://colab.research.google.com/github/yongjaeahn/PythonCoding/blob/main/korean/source/06_03_%EC%88%98%ED%95%99_%EB%A6%AC%EC%8A%A4%ED%8A%B8%EC%99%80_numpy_%EB%B0%B0%EC%97%B4_%EB%8B%A4%EB%A3%A8%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

	리스트와 numpy 배열 다루기

형상 확인

In [ ]:
import numpy as np

listVector = [1,2,3,4,5] 
arrayVector = np.arange(1,6)
print("arrayVector :", arrayVector)

print("len(listVector) :", len(listVector))
print("len(arrayVector) :", len(arrayVector))

arrayVector : [1 2 3 4 5]
len(listVector) : 5
len(arrayVector) : 5


In [ ]:
import numpy as np

listMatrix2d = [[1,2,3],[4,5,6]]
arrayMatrix2d = np.arange(1,7).reshape(2,3)
print("arrayMatrix2d :\n", arrayMatrix2d)

print("np.ndim(listMatrix2d) :", np.ndim(listMatrix2d))
print("np.ndim(arrayMatrix2d) :", np.ndim(arrayMatrix2d))
print("np.size(listMatrix2d) :", np.size(listMatrix2d))
print("np.size(arrayMatrix2d) :", np.size(arrayMatrix2d))
print("np.shape(listMatrix2d) :", np.shape(listMatrix2d))
print("np.shape(arrayMatrix2d) :", np.shape(arrayMatrix2d))

arrayMatrix2d :
 [[1 2 3]
 [4 5 6]]
np.ndim(listMatrix2d) : 2
np.ndim(arrayMatrix2d) : 2
np.size(listMatrix2d) : 6
np.size(arrayMatrix2d) : 6
np.shape(listMatrix2d) : (2, 3)
np.shape(arrayMatrix2d) : (2, 3)


In [4]:
import numpy as np

arrayMatrix2d = np.arange(1,7).reshape(2,3)
print("arrayMatrix2d :\n", arrayMatrix2d)

print("arrayMatrix2d.ndim :", arrayMatrix2d.ndim)
print("arrayMatrix2d.size :", arrayMatrix2d.size)
print("arrayMatrix2d.shape :", arrayMatrix2d.shape)
print("arrayMatrix2d.shape :", arrayMatrix2d.len)

arrayMatrix2d :
 [[1 2 3]
 [4 5 6]]
arrayMatrix2d.ndim : 2
arrayMatrix2d.size : 6
arrayMatrix2d.shape : (2, 3)


AttributeError: ignored

In [ ]:
shape = np.shape(arrayMatrix2d)
print("type(shape) :", type(shape))
print("행의 길이 (shape[0]) :", shape[0], ", 열의 길이 (shape[1]) :", shape[1])

rowLen, columnLen = np.shape(arrayMatrix2d)
print("type(rowLen) :", type(rowLen), "type(columnLen) :", type(columnLen))
print("행의 길이 (rowLen) :", rowLen, ", 열의 길이 (columnLen) :", columnLen)

type(shape) : <class 'tuple'>
행의 길이 (shape[0]) : 2 , 열의 길이 (shape[1]) : 3
type(rowLen) : <class 'int'> type(columnLen) : <class 'int'>
행의 길이 (rowLen) : 2 , 열의 길이 (columnLen) : 3


In [ ]:
import numpy as np

arrayMatrix3d = np.arange(1,25).reshape(2,4,3)
print("arrayMatrix3d :\n", arrayMatrix3d)
print("np.shape(arrayMatrix3d) :", np.shape(arrayMatrix3d))

shape = np.shape(arrayMatrix3d)
print("x축의 길이 :", shape[0], ", y축의 길이 :", shape[1], ", z축의 길이 :", shape[2])

xLen, yLen, zLen = np.shape(arrayMatrix3d)
print("x축의 길이 :", xLen, ", y축의 길이 :", yLen, ", z축의 길이 :", zLen)

arrayMatrix3d :
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
np.shape(arrayMatrix3d) : (2, 4, 3)
x축의 길이 : 2 , y축의 길이 : 4 , z축의 길이 : 3
x축의 길이 : 2 , y축의 길이 : 4 , z축의 길이 : 3


In [ ]:
for length in shape:
    print("길이 :", length)

for i in range(len(shape)):
    print(i+1, "차원 길이 :", shape[i])

길이 : 2
길이 : 4
길이 : 3
1 차원 길이 : 2
2 차원 길이 : 4
3 차원 길이 : 3


In [ ]:
print("enumerate(shape) :", list(enumerate(shape)))

for i, dim in enumerate(shape):
    print(i+1, "차원 길이 :", dim)

enumerate(shape) : [(0, 2), (1, 4), (2, 3)]
1 차원 길이 : 2
2 차원 길이 : 4
3 차원 길이 : 3


In [ ]:
print("3차원 행렬 :\n", arrayMatrix3d)
print("하부 2차원 행렬 :\n", arrayMatrix3d[0])
print("하부 1차원 행렬(벡터) :\n", arrayMatrix3d[0][0])

3차원 행렬 :
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
하부 2차원 행렬 :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
하부 1차원 행렬(벡터) :
 [1 2 3]


In [ ]:
print("1차원 길이 :", len(arrayMatrix3d))
print("2차원 길이 :", len(arrayMatrix3d[0]))
print("3차원 길이 :", len(arrayMatrix3d[0][0]))

1차원 길이 : 2
2차원 길이 : 4
3차원 길이 : 3


In [ ]:
returnedValues = (40,50,60)
print("returnedValues : ", returnedValues)

returnedValues :  (40, 50, 60)


생성

조회

In [ ]:
import numpy as np

listVector = [1,2,3,4,5,6,7,8,9,10]
arrayVector = np.array([1,2,3,4,5,6,7,8,9,10])

print("첫 요소 :", listVector[0], arrayVector[0])
print("마지막 요소 :", listVector[-1], arrayVector[-1])
print("3~7번째 요소 :", listVector[2:7], arrayVector[2:7])
print("1~7번째 요소 :", listVector[:7], arrayVector[:7])
print("7번째~마지막 요소 :", listVector[6:], arrayVector[6:])
print("2~8번째 요소 중 짝수번째 요소 : ", listVector[1:8:2], arrayVector[1:8:2])
print("마지막에서 2~8번째 요소 중 짝수번째 요소 :", listVector[-2:-9:-2], arrayVector[-2:-9:-2])
print("전체 요소 중 홀수번째 요소 :",listVector[::2], arrayVector[::2])

첫 요소 : 1 1
마지막 요소 : 10 10
3~7번째 요소 : [3, 4, 5, 6, 7] [3 4 5 6 7]
1~7번째 요소 : [1, 2, 3, 4, 5, 6, 7] [1 2 3 4 5 6 7]
7번째~마지막 요소 : [7, 8, 9, 10] [ 7  8  9 10]
2~8번째 요소 중 짝수번째 요소 :  [2, 4, 6, 8] [2 4 6 8]
마지막에서 2~8번째 요소 중 짝수번째 요소 : [9, 7, 5, 3] [9 7 5 3]
전체 요소 중 홀수번째 요소 : [1, 3, 5, 7, 9] [1 3 5 7 9]


In [ ]:
print("첫 3개의 요소와 마지막 3개의 요소 : ", arrayVector[[0,1,2,-1,-2,-3]])

첫 3개의 요소와 마지막 3개의 요소 :  [ 1  2  3 10  9  8]


In [ ]:
sampleString = "긴 문자열입니다."
print(sampleString[2:5])

문자열


In [ ]:
import numpy as np

listMatrix2d = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]]
arrayMatrix2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("arrayMatrix2d :\n", arrayMatrix2d)

print("첫 요소 :", listMatrix2d[0][0], arrayMatrix2d[0][0], arrayMatrix2d[0,0])
print("2행 3열 요소 :", listMatrix2d[1][2], arrayMatrix2d[1][2], arrayMatrix2d[1,2])
print("마지막 요소 :", listMatrix2d[-1][-1], arrayMatrix2d[-1][-1], arrayMatrix2d[-1,-1])

arrayMatrix2d :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
첫 요소 : 1 1 1
2행 3열 요소 : 8 8 8
마지막 요소 : 25 25 25


In [ ]:
print("1행벡터 :", listMatrix2d[0], arrayMatrix2d[0])
print("3행벡터 :", listMatrix2d[2][:], arrayMatrix2d[2][:])
print("2~4행벡터(리스트) :", listMatrix2d[1:4])
print("2~4행벡터(배열) :\n", arrayMatrix2d[1:4,:])

1행벡터 : [1, 2, 3, 4, 5] [1 2 3 4 5]
3행벡터 : [11, 12, 13, 14, 15] [11 12 13 14 15]
2~4행벡터(리스트) : [[6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
2~4행벡터(배열) :
 [[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
print("1열벡터 :", listMatrix2d[:][0], arrayMatrix2d[:][0])
print("3열벡터 :", listMatrix2d[:][2], arrayMatrix2d[:][2])
print("2~4열벡터(리스트) :", listMatrix2d[:][1:4])
print("2~4열벡터(배열) :\n", arrayMatrix2d[:][1:4])

1열벡터 : [1, 2, 3, 4, 5] [1 2 3 4 5]
3열벡터 : [11, 12, 13, 14, 15] [11 12 13 14 15]
2~4열벡터(리스트) : [[6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
2~4열벡터(배열) :
 [[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
print("1열벡터 :", arrayMatrix2d[:,0])
print("3열벡터 :", arrayMatrix2d[:,2])
print("2~4열벡터(배열) :\n", arrayMatrix2d[:,1:4])

1열벡터 : [ 1  6 11 16 21]
3열벡터 : [ 3  8 13 18 23]
2~4열벡터(배열) :
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]


In [ ]:
print("2~3 행 슬라이싱(1:3) + 2~4 열 슬라이싱(1:4) :\n", arrayMatrix2d[1:3,1:4])

2~3 행 슬라이싱(1:3) + 2~4 열 슬라이싱(1:4) :
 [[ 7  8  9]
 [12 13 14]]


In [ ]:
print("첫 3개의 요소와 마지막 3개의 요소 : ", arrayMatrix2d[[0,0,0,-1,-1,-1],[0,1,2,-1,-2,-3]])

첫 3개의 요소와 마지막 3개의 요소 :  [ 1  2  3 25 24 23]


In [ ]:
print(arrayMatrix2d < 10)

[[ True  True  True  True  True]
 [ True  True  True  True False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [ ]:
print(arrayMatrix2d[arrayMatrix2d < 10])

mask = arrayMatrix2d < 10
print(arrayMatrix2d[mask])

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
mask = (arrayMatrix2d < 10) | (arrayMatrix2d > 20)
print(arrayMatrix2d[mask])

[ 1  2  3  4  5  6  7  8  9 21 22 23 24 25]


In [ ]:
import numpy as np

subjects = np.array(["학번","국어","영어","수학","사탐","과탐"])
scores = np.array([[1,90,80,95,100,95],[2,100,80,85,90,95],[3,95,100,80,85,90],[4,80,95,100,90,85],[5,85,80,90,100,95]])
print("성적 :\n", scores)

maskColumn = (subjects == "학번") | (subjects == "수학") | (subjects == "과탐")
print(scores[:,maskColumn])

성적 :
 [[  1  90  80  95 100  95]
 [  2 100  80  85  90  95]
 [  3  95 100  80  85  90]
 [  4  80  95 100  90  85]
 [  5  85  80  90 100  95]]
[[  1  95  95]
 [  2  85  95]
 [  3  80  90]
 [  4 100  85]
 [  5  90  95]]


In [ ]:
maskRow = scores[:,4] == 100
print(maskRow)
print(scores[maskRow])

[ True False False False  True]
[[  1  90  80  95 100  95]
 [  5  85  80  90 100  95]]


In [ ]:
import numpy as np

employeeList = [320811, "안용제", "010-1234-5678", "서울시 영등포구 당산동", 99.5]
print("리스트(list) : ", employeeList)

employeeArray = np.array([320811, "안용제", "010-1234-5678", "서울시 영등포구 당산동", 99.5])
print("배열(array) : ", employeeArray)

리스트(list) :  [320811, '안용제', '010-1234-5678', '서울시 영등포구 당산동', 99.5]
배열(array) :  ['320811' '안용제' '010-1234-5678' '서울시 영등포구 당산동' '99.5']


In [ ]:
print("리스트의 성적 - 10 : ", employeeList[4] - 10)

print("배열의 성적 - 10 : ", employeeArray[4] - 10)

리스트의 성적 - 10 :  89.5


TypeError: ignored

수정

In [ ]:
listMatrix2d = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]]

print("listMatrix2d (수정전):\n", listMatrix2d)
listMatrix2d[0][0] = -999
print("listMatrix2d (수정후):\n", listMatrix2d)

listMatrix2d (수정전):
 [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]
listMatrix2d (수정후):
 [[-999, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]


In [ ]:
import numpy as np

arrayMatrix2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])

print("arrayMatrix2d (수정전) :\n", arrayMatrix2d)
arrayMatrix2d[1][2] = -888
arrayMatrix2d[-1,-1] = -777
print("arrayMatrix2d (수정후):\n", arrayMatrix2d)

arrayMatrix2d (수정전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (수정후):
 [[   1    2    3    4    5]
 [   6    7 -888    9   10]
 [  11   12   13   14   15]
 [  16   17   18   19   20]
 [  21   22   23   24 -777]]


In [ ]:
arrayMatrix2d[0] = 1
arrayMatrix2d[2:3,:] = -1
print("arrayMatrix2d (수정후):\n", arrayMatrix2d)

arrayMatrix2d (수정후):
 [[ 1  1  1  1  1]
 [ 6  7  8  9 10]
 [-1 -1 -1 -1 -1]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
arrayMatrix2d[:,0] = 2
arrayMatrix2d[:,2:3] = -2
print("arrayMatrix2d (수정후):\n", arrayMatrix2d)

arrayMatrix2d (수정후):
 [[ 2  1 -2  1  1]
 [ 2  7 -2  9 10]
 [ 2 -1 -2 -1 -1]
 [ 2 17 -2 19 20]
 [ 2 22 -2 24 25]]


In [ ]:
arrayMatrix2d[1:3,1:4] = 100
print("arrayMatrix2d (수정후):\n", arrayMatrix2d)

arrayMatrix2d (수정후):
 [[  2   1  -2   1   1]
 [  2 100 100 100  10]
 [  2 100 100 100  -1]
 [  2  17  -2  19  20]
 [  2  22  -2  24  25]]


In [ ]:
 arrayMatrix2d[[0,0,0,-1,-1,-1],[0,1,2,-1,-2,-3]] = -100
 print("arrayMatrix2d (수정후):\n", arrayMatrix2d)

arrayMatrix2d (수정후):
 [[-100 -100 -100    1    1]
 [   2  100  100  100   10]
 [   2  100  100  100   -1]
 [   2   17   -2   19   20]
 [   2   22 -100 -100 -100]]


In [ ]:
mask = arrayMatrix2d == -100
arrayMatrix2d[mask] = 100
print("arrayMatrix2d (수정후):\n", arrayMatrix2d)

arrayMatrix2d (수정후):
 [[100 100 100   1   1]
 [  2 100 100 100  10]
 [  2 100 100 100  -1]
 [  2  17  -2  19  20]
 [  2  22 100 100 100]]


삭제

In [ ]:
listVector = [1,2,3,4,5,6,7,8,9,10]
print("listVector (삭제전): ", listVector)
del listVector[3]     # 인덱스로 삭제
print("listVector (인덱스 3 즉 4번째 요소 삭제후): ", listVector)
listVector.remove(10) #  값으로 삭제
print("listVector (값 10으로 삭제후): ", listVector)

listVector (삭제전):  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
listVector (인덱스 3 즉 4번째 요소 삭제후):  [1, 2, 3, 5, 6, 7, 8, 9, 10]
listVector (값 10으로 삭제후):  [1, 2, 3, 5, 6, 7, 8, 9]


In [ ]:
import numpy as np

arrayMatrix2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("arrayMatrix2d (삭제전) :\n", arrayMatrix2d)

arrayMatrix2d = np.delete(arrayMatrix2d,1,axis=0)
print("arrayMatrix2d (인덱스 1 즉 2행 삭제후) :\n", arrayMatrix2d)
arrayMatrix2d = np.delete(arrayMatrix2d,-1,axis=1)
print("arrayMatrix2d (인덱스 -1 즉 마지막열 삭제후) :\n", arrayMatrix2d)
arrayMatrix2d = np.delete(arrayMatrix2d,[1,3],axis=0)
print("arrayMatrix2d (인덱스 1과 3 즉 2행과 4행 삭제후) :\n", arrayMatrix2d)

arrayMatrix2d (삭제전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (인덱스 1 즉 2행 삭제후) :
 [[ 1  2  3  4  5]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (인덱스 -1 즉 마지막열 삭제후) :
 [[ 1  2  3  4]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]
arrayMatrix2d (인덱스 1과 3 즉 2행과 4행 삭제후) :
 [[ 1  2  3  4]
 [16 17 18 19]]


추가

In [ ]:
listVector = [1,2,4,5]
print("listVector (추가전): ", listVector)
listVector.append(6)              # 리스트의 맨뒤에 값을 추가
print("listVector (6을 추가한 후): ", listVector)
listVector.insert(2,3)            # 리스트의 3번째 요소로 3을 추가
print("listVector (3을 추가한 후): ", listVector)
listVector.extend([7,8])          # 리스트의 맨뒤에 7과 8을 리스트로 확장
print("listVector (7과 8의 리스트를 확장한 후): ", listVector)
listVector = [-1,0] + listVector + [9,10]  # -1,0의 리스트와 9,10의 리스트를 앞뒤로 이어붙임
print("listVector (-1,0 리스트와 9~10 리스트를 이어붙인 후): ", listVector)

listVector (추가전):  [1, 2, 4, 5]
listVector (6을 추가한 후):  [1, 2, 4, 5, 6]
listVector (3을 추가한 후):  [1, 2, 3, 4, 5, 6]
listVector (7과 8의 리스트를 확장한 후):  [1, 2, 3, 4, 5, 6, 7, 8]
listVector (-1,0 리스트와 9~10 리스트를 이어붙인 후):  [-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
import numpy as np

arrayMatrix2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("arrayMatrix2d (추가전) :\n", arrayMatrix2d)
newRow2d = np.array([[26,27,28,29,30],[31,32,33,34,35]])
print("newRow2d :\n", newRow2d)
arrayMatrix2d = np.append(arrayMatrix2d,newRow2d,axis=0)
print("arrayMatrix2d (신규행 추가후) :\n", arrayMatrix2d)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
newRow2d :
 [[26 27 28 29 30]
 [31 32 33 34 35]]
arrayMatrix2d (신규행 추가후) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [ ]:
import numpy as np

arrayMatrix2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("arrayMatrix2d (추가전) :\n", arrayMatrix2d)
newRow2d = np.array([26,27,28,29,30])
print("newRow2d :\n", newRow2d)
arrayMatrix2d = np.append(arrayMatrix2d,[newRow2d],axis=0)
print("arrayMatrix2d (신규행 추가후) :\n", arrayMatrix2d)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
newRow2d :
 [26 27 28 29 30]
arrayMatrix2d (신규행 추가후) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [ ]:
import numpy as np

arrayMatrix2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("arrayMatrix2d (추가전) :\n", arrayMatrix2d)
newRow2d = np.array([26,27,28,29,30],[31,32,33,34,35])
print("newRow2d :\n", newRow2d)
arrayMatrix2d = np.append(arrayMatrix2d,[newRow2d],axis=0)
print("arrayMatrix2d (신규행 추가후) :\n", arrayMatrix2d)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


TypeError: ignored

In [ ]:
import numpy as np

arrayMatrix2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("arrayMatrix2d (추가전) :\n", arrayMatrix2d)
newRow2d = np.array([[26,27,28,29,30],[31,32,33,34,35]])
print("newRow2d :\n", newRow2d)
arrayMatrix2d = np.append(arrayMatrix2d,[newRow2d],axis=0)
print("arrayMatrix2d (신규행 추가후) :\n", arrayMatrix2d)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
newRow2d :
 [[26 27 28 29 30]
 [31 32 33 34 35]]


ValueError: ignored

In [ ]:
import numpy as np

arrayMatrix2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("arrayMatrix2d (추가전) :\n", arrayMatrix2d)
newRow2d = np.array([[26,27,28,29,30]])
print("newRow2d :\n", newRow2d)
arrayMatrix2d = np.append(arrayMatrix2d,newRow2d,axis=0)
print("arrayMatrix2d (신규행 추가후) :\n", arrayMatrix2d)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
newRow2d :
 [[26 27 28 29 30]]
arrayMatrix2d (신규행 추가후) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [ ]:
import numpy as np

arrayMatrix2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("arrayMatrix2d (추가전) :\n", arrayMatrix2d)
newColumn2d = np.array([[26],[27],[28],[29],[30]])
print("newColumn2d :\n", newColumn2d)
arrayMatrix2d = np.append(arrayMatrix2d,newColumn2d,axis=1)
print("arrayMatrix2d (신규열 추가후) :\n", arrayMatrix2d)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
newColumn2d :
 [[26]
 [27]
 [28]
 [29]
 [30]]
arrayMatrix2d (신규열 추가후) :
 [[ 1  2  3  4  5 26]
 [ 6  7  8  9 10 27]
 [11 12 13 14 15 28]
 [16 17 18 19 20 29]
 [21 22 23 24 25 30]]


In [ ]:
import numpy as np

arrayMatrix2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("arrayMatrix2d (추가전) :\n", arrayMatrix2d)
newRow2d = np.array([[26,27,28,29,30],[31,32,33,34,35]])
print("newRow2d :\n", newRow2d)
newColumn2d = np.transpose(newRow2d)
print("newColumn2d :\n", newColumn2d)
arrayMatrix2d = np.append(arrayMatrix2d,newColumn2d,axis=1)
print("arrayMatrix2d (신규열 추가후) :\n", arrayMatrix2d)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
newRow2d :
 [[26 27 28 29 30]
 [31 32 33 34 35]]
newColumn2d :
 [[26 31]
 [27 32]
 [28 33]
 [29 34]
 [30 35]]
arrayMatrix2d (신규열 추가후) :
 [[ 1  2  3  4  5 26 31]
 [ 6  7  8  9 10 27 32]
 [11 12 13 14 15 28 33]
 [16 17 18 19 20 29 34]
 [21 22 23 24 25 30 35]]


In [ ]:
import numpy as np

arrayMatrix2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])

newRow2d01 = np.array([[26,27,28,29,30]])
newRow2d02 = np.array([[31,32,33,34,35],[36,37,38,39,40]])
arrayMatrix2d = np.concatenate([arrayMatrix2d,newRow2d01,newRow2d02],axis= 0)
arrayMatrix2d = np.vstack((arrayMatrix2d,newRow2d01,newRow2d02))

arrayMatrix2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])

newColumn2d01 = np.transpose(newRow2d01)
newColumn2d02 = np.transpose(newRow2d02)
arrayMatrix2d = np.concatenate([arrayMatrix2d,newColumn2d01,newColumn2d02],axis= 1)
arrayMatrix2d = np.hstack((arrayMatrix2d,newColumn2d01,newColumn2d02))

In [ ]:
import numpy as np

arrayMatrix2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("arrayMatrix2d (추가전) :\n", arrayMatrix2d)

newRow2d = np.array([[26,27,28,29,30],[31,32,33,34,35]])
arrayMatrix2d = np.insert(arrayMatrix2d,1,newRow2d,axis=0)
print("arrayMatrix2d (2행으로 신규행 추가후) :\n", arrayMatrix2d)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (2행으로 신규행 추가후) :
 [[ 1  2  3  4  5]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
import numpy as np

arrayMatrix2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("arrayMatrix2d (추가전) :\n", arrayMatrix2d)

newRow2d = np.array([[26,27,28,29,30],[31,32,33,34,35]])
newColumn2d = np.transpose(newRow2d)
arrayMatrix2d = np.insert(arrayMatrix2d,1,newColumn2d,axis=1)
print("arrayMatrix2d (2열로 신규열 추가후) :\n", arrayMatrix2d)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


ValueError: ignored

In [ ]:
import numpy as np

arrayMatrix2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("arrayMatrix2d (추가전) :\n", arrayMatrix2d)

newRow2d = np.array([[26,27,28,29,30],[31,32,33,34,35]])
newColumn2d = np.transpose(newRow2d)
arrayMatrix2d = np.insert(arrayMatrix2d,[1,2],newColumn2d,axis=1)
print("arrayMatrix2d (2열과 3열로 신규열 추가후) :\n", arrayMatrix2d)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (2열과 3열로 신규열 추가후) :
 [[ 1 26  2 31  3  4  5]
 [ 6 27  7 32  8  9 10]
 [11 28 12 33 13 14 15]
 [16 29 17 34 18 19 20]
 [21 30 22 35 23 24 25]]


In [ ]:
import numpy as np

arrayMatrix2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("arrayMatrix2d (추가전) :\n", arrayMatrix2d)

newRow2d = np.array([[26,27,28,29,30],[31,32,33,34,35]])
newColumn2d = np.transpose(newRow2d)
arrayMatrix2d = np.insert(arrayMatrix2d,[1,1],newColumn2d,axis=1)
print("arrayMatrix2d (2열로 신규열 추가후) :\n", arrayMatrix2d)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (2열로 신규열 추가후) :
 [[ 1 26 31  2  3  4  5]
 [ 6 27 32  7  8  9 10]
 [11 28 33 12 13 14 15]
 [16 29 34 17 18 19 20]
 [21 30 35 22 23 24 25]]


In [ ]:
import numpy as np

arrayMatrix2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("arrayMatrix2d (추가전) :\n", arrayMatrix2d)

newRow2d = np.array([[26,27,28,29,30]])
newColumn2d = np.transpose(newRow2d)

arrayMatrix2d = np.insert(arrayMatrix2d,[0,2,3],newColumn2d01,axis=1)
print("arrayMatrix2d (1열과 3열과 4열에 신규열 추가후) :\n", arrayMatrix2d)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (1열과 3열과 4열에 신규열 추가후) :
 [[26  1  2 26  3 26  4  5]
 [27  6  7 27  8 27  9 10]
 [28 11 12 28 13 28 14 15]
 [29 16 17 29 18 29 19 20]
 [30 21 22 30 23 30 24 25]]


In [ ]:
import numpy as np

arrayMatrix2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("arrayMatrix2d (추가전) :\n", arrayMatrix2d)

newRow2d = np.array([[26,27,28,29,30],[31,32,33,34,35]])
arrayMatrix2d = np.insert(arrayMatrix2d,[1,3],newRow2d,axis=0)
print("arrayMatrix2d (2행과 4행으로 신규행 추가후) :\n", arrayMatrix2d)

arrayMatrix2d (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (2행과 4행으로 신규행 추가후) :
 [[ 1  2  3  4  5]
 [26 27 28 29 30]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [31 32 33 34 35]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
listVector = []
print("listVector (빈 벡터) :\n", listVector)

listVector.append(1)        # 벡터의 요소값들을 외부에서 읽어 온다고 가정
listVector.append(2)
listVector.append(3)
print("listVector (값을 읽어와 생성한 벡터) :\n", listVector)

listVector (빈 벡터) :
 []
listVector (값을 읽어와 생성한 벡터) :
 [1, 2, 3]


In [ ]:
import numpy as np

# 행렬의 크기를 외부에서 읽어 온다고 가정
row = 2       
column = 3

arrayMatrix2d = np.empty(shape=(row, column))
print("arrayMatrix2d (빈 배열) :\n", arrayMatrix2d)

# 행렬의 요소값들을 외부에서 읽어 온다고 가정
for i in range(row):
    arrayMatrix2d[i] = np.array(np.arange(i * column,i * column + column))

print("arrayMatrix2d (값을 읽어와 생성한 배열) :\n", arrayMatrix2d)

arrayMatrix2d (빈 배열) :
 [[2.5013579e-316 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]]
arrayMatrix2d (값을 읽어와 생성한 배열) :
 [[0. 1. 2.]
 [3. 4. 5.]]


numpy 기타

In [ ]:
import numpy as np

arrayMatrix2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("arrayMatrix2d (변경전) :\n", arrayMatrix2d)
arrayMatrix2d = np.flipud(arrayMatrix2d)
print("arrayMatrix2d (행렬의 상하 변경후) :\n", arrayMatrix2d)

arrayMatrix2d (변경전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (행렬의 상하 변경후) :
 [[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [ ]:
import numpy as np

arrayMatrix2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("arrayMatrix2d (변경전) :\n", arrayMatrix2d)
arrayMatrix2d = np.fliplr(arrayMatrix2d)
print("arrayMatrix2d (행렬의 좌우 변경후) :\n", arrayMatrix2d)

arrayMatrix2d (변경전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (행렬의 좌우 변경후) :
 [[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]


In [ ]:
import numpy as np

arrayMatrix2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("arrayMatrix2d (변경전) :\n", arrayMatrix2d)
arrayMatrix2d = np.flip(arrayMatrix2d)
print("arrayMatrix2d (행렬의 앞뒤 변경후) :\n", arrayMatrix2d)

arrayMatrix2d (변경전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (행렬의 앞뒤 변경후) :
 [[25 24 23 22 21]
 [20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [ ]:
import numpy as np

arrayMatrix3d = np.arange(1,28).reshape(3,3,3)
print("arrayMatrix3d (변경전) :\n", arrayMatrix3d)
arrayMatrix3d = np.flip(arrayMatrix3d,axis=2)
print("arrayMatrix3d (3차원 행렬의 3번째 축 기준 앞뒤 변경후) :\n", arrayMatrix3d)

arrayMatrix3d (변경전) :
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
arrayMatrix3d (3차원 행렬의 3번째 축 기준 앞뒤 변경후) :
 [[[ 3  2  1]
  [ 6  5  4]
  [ 9  8  7]]

 [[12 11 10]
  [15 14 13]
  [18 17 16]]

 [[21 20 19]
  [24 23 22]
  [27 26 25]]]


In [ ]:
import numpy as np

arrayMatrix3d = np.arange(1,28).reshape(3,3,3)
print("arrayMatrix3d (변경전) :\n", arrayMatrix3d)
arrayMatrix3d = np.flip(arrayMatrix3d,axis=(0,2))
print("arrayMatrix3d (3차원 행렬의 1,3번째 축 기준 앞뒤 변경후) :\n", arrayMatrix3d)

arrayMatrix3d (변경전) :
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
arrayMatrix3d (3차원 행렬의 1,3번째 축 기준 앞뒤 변경후) :
 [[[21 20 19]
  [24 23 22]
  [27 26 25]]

 [[12 11 10]
  [15 14 13]
  [18 17 16]]

 [[ 3  2  1]
  [ 6  5  4]
  [ 9  8  7]]]


In [ ]:
import numpy as np

arrayMatrix2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("arrayMatrix2d (변경전) :\n", arrayMatrix2d)
arrayMatrix2d = np.roll(arrayMatrix2d,shift=3)
print("arrayMatrix2d (행렬의 앞뒤 변경후) :\n", arrayMatrix2d)

arrayMatrix2d (변경전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
arrayMatrix2d (행렬의 앞뒤 변경후) :
 [[23 24 25  1  2]
 [ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]]


In [ ]:
import numpy as np

arrayMatrix2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("arrayMatrix2d (회전전) :\n", arrayMatrix2d)
arrayMatrix2d = np.rot90(arrayMatrix2d,k=1)
print("arrayMatrix2d (시계 반대방향 90도 회전후) :\n", arrayMatrix2d)
arrayMatrix2d = np.rot90(arrayMatrix2d,k=-2)
print("arrayMatrix2d (시계 방향 180도 회전후) :\n", arrayMatrix2d)

arrayMatrix2d (회전전) :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arrayMatrix2d (시계 반대방향 90도 회전후) :
 [[3 6 9]
 [2 5 8]
 [1 4 7]]
arrayMatrix2d (시계 방향 180도 회전후) :
 [[7 4 1]
 [8 5 2]
 [9 6 3]]


In [ ]:
import numpy as np

arrayMatrix3d = np.arange(1,28).reshape(3,3,3)
print("arrayMatrix3d (회전전) :\n", arrayMatrix3d)
arrayMatrix3d = np.rot90(arrayMatrix3d,k=1,axes=(0,1))
print("arrayMatrix3d (3차원 행렬의 1,2번째 축 기준 90도 회전후) :\n", arrayMatrix3d)

arrayMatrix3d (회전전) :
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
arrayMatrix3d (3차원 행렬의 1,2번째 축 기준 90도 회전후) :
 [[[ 7  8  9]
  [16 17 18]
  [25 26 27]]

 [[ 4  5  6]
  [13 14 15]
  [22 23 24]]

 [[ 1  2  3]
  [10 11 12]
  [19 20 21]]]


In [ ]:
import numpy as np

arrayMatrix2d = np.array([[1,2],[3,4]])
print("arrayMatrix2d (반복전) :\n", arrayMatrix2d)
arrayMatrix2d = np.tile(arrayMatrix2d, reps=3)
print("arrayMatrix2d (3열로 반복후) :\n", arrayMatrix2d)

arrayMatrix2d = np.array([[1,2],[3,4]])
arrayMatrix2d = np.tile(arrayMatrix2d, reps=(2,3))
print("arrayMatrix2d (2행 3열로 반복후) :\n", arrayMatrix2d)

arrayMatrix2d (반복전) :
 [[1 2]
 [3 4]]
arrayMatrix2d (3열로 반복후) :
 [[1 2 1 2 1 2]
 [3 4 3 4 3 4]]
arrayMatrix2d (2행 3열로 반복후) :
 [[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [ ]:
import numpy as np

arrayVector = np.arange(10)
print("arrayVector (섞기전) :\n", arrayVector)
np.random.shuffle(arrayVector)
print("arrayVector (섞은후) :\n", arrayVector)

arrayVector (섞기전) :
 [0 1 2 3 4 5 6 7 8 9]
arrayVector (섞은후) :
 [3 8 0 4 1 2 7 5 9 6]


In [ ]:
import random

listVector = [0,1,2,3,4,5,6,7,8,9]
print("listVector (섞기전) :\n", listVector)
random.shuffle(listVector)
print("listVector (섞은후) :\n", listVector)

listVector (섞기전) :
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
listVector (섞은후) :
 [5, 0, 2, 1, 9, 6, 4, 3, 7, 8]


In [ ]:
import numpy as np

arrayMatrix2d = np.arange(1,37).reshape(6,6)
print("arrayMatrix2d :\n", arrayMatrix2d)

splitedMatrix2d = np.split(arrayMatrix2d, 2, axis=0)
print("splitedMatrix2d[0] :\n", splitedMatrix2d[0])
print("splitedMatrix2d[1] :\n", splitedMatrix2d[1])

arrayMatrix2d :
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
splitedMatrix2d[0] :
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
splitedMatrix2d[1] :
 [[19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [ ]:
splitedMatrix2d = np.split(arrayMatrix2d, (1,3), axis=0)
print("splitedMatrix2d[0] :\n", splitedMatrix2d[0])
print("splitedMatrix2d[1] :\n", splitedMatrix2d[1])
print("splitedMatrix2d[2] :\n", splitedMatrix2d[2])

splitedMatrix2d[0] :
 [[1 2 3 4 5 6]]
splitedMatrix2d[1] :
 [[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
splitedMatrix2d[2] :
 [[19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [ ]:
import numpy as np

arrayVector = np.array([1,2,3,4,5])
arrayMatrix2d = np.array([[-2,-1,0,1,2],[1,2,3,4,5]])

print(np.any(arrayVector < 0))        # 0보다 작은 값이 있는지 확인
print(np.any(arrayMatrix2d < 0))

# 두 배열의 요소가 같은 값이 하나라도 있는지 확인
equalBooleanIndex = np.array([1,2,3]) == np.array([-1,2,-3])
print("equalBooleanIndex :\n",equalBooleanIndex)
np.any(equalBooleanIndex)

False
True
equalBooleanIndex :
 [False  True False]


True

In [ ]:
import numpy as np

arrayVector = np.array([1,0,0,0,0])
arrayMatrix2d = np.zeros(shape=(2,3))
print("arrayMatrix2d : \n", arrayMatrix2d)

print(np.all(arrayVector == 0))        # 모든 값이 0과 같은지 확인
print(np.all(arrayMatrix2d == 0))

# 두 배열의 요소가 모두 같은 값인지 확인
equalBooleanIndex = np.array([1,2,3]) == np.array([-1,2,-3])
print("equalBooleanIndex :\n",equalBooleanIndex)
np.all(equalBooleanIndex)

arrayMatrix2d : 
 [[0. 0. 0.]
 [0. 0. 0.]]
False
True
equalBooleanIndex :
 [False  True False]


False

In [ ]:
import numpy as np

arrayMatrix2d01 = np.array([[-2,-1,0,1,2],[1,2,3,4,5]])
arrayMatrix2d02 = np.array([[1,0,0,0,1],[5,4,3,2,1]])
arrayMatrix2d03 = arrayMatrix2d01 / arrayMatrix2d02
print("나누어진 행렬 : \n", arrayMatrix2d03)

# Not a Number(nan)가 있는지 불리언 인덱스로 확인
isnanBooleanIndex = np.isnan(arrayMatrix2d03)          
print("isnanBooleanIndex : \n", isnanBooleanIndex)
print("nan이 없는 값만 발췌 : \n", arrayMatrix2d03[~isnanBooleanIndex])

나누어진 행렬 : 
 [[-2.  -inf  nan  inf  2. ]
 [ 0.2  0.5  1.   2.   5. ]]
isnanBooleanIndex : 
 [[False False  True False False]
 [False False False False False]]
nan이 없는 값만 발췌 : 
 [-2.  -inf  inf  2.   0.2  0.5  1.   2.   5. ]


<ipython-input-44-666ee8f2a428>:5: RuntimeWarning: divide by zero encountered in true_divide
  arrayMatrix2d03 = arrayMatrix2d01 / arrayMatrix2d02
<ipython-input-44-666ee8f2a428>:5: RuntimeWarning: invalid value encountered in true_divide
  arrayMatrix2d03 = arrayMatrix2d01 / arrayMatrix2d02


In [ ]:
# 무한대(inf,-inf)나 Not a Number(nan)가 없는지 불리언 인덱스로 확인
isfiniteBooleanIndex = np.isfinite(arrayMatrix2d03)
print("isfiniteBooleanIndex : \n", isfiniteBooleanIndex)
print("유한한 값만 발췌 : \n", arrayMatrix2d03[isfiniteBooleanIndex])

isfiniteBooleanIndex : 
 [[ True False False False  True]
 [ True  True  True  True  True]]
유한한 값만 발췌 : 
 [-2.   2.   0.2  0.5  1.   2.   5. ]


In [ ]:
print("nan인 값을 0으로 바꾼 행렬 :\n",np.where(np.isnan(arrayMatrix2d03), 0, arrayMatrix2d03))
print("유한하지 않은 값을 0으로 바꾼 행렬 :\n",np.where(~np.isfinite(arrayMatrix2d03), 0, arrayMatrix2d03))

nan인 값을 0으로 바꾼 행렬 :
 [[-2.  -inf  0.   inf  2. ]
 [ 0.2  0.5  1.   2.   5. ]]
유한하지 않은 값을 0으로 바꾼 행렬 :
 [[-2.   0.   0.   0.   2. ]
 [ 0.2  0.5  1.   2.   5. ]]


In [ ]:
print("nan이 포함되지 않은 배열 비교\n",arrayMatrix2d02 == arrayMatrix2d02)
print("nan이 포함되지 않은 배열 비교\n",np.array_equal(arrayMatrix2d02,arrayMatrix2d02))

print("nan이 포함된 배열 비교\n",arrayMatrix2d03 == arrayMatrix2d03)
print("nan이 포함된 배열 비교\n",np.array_equal(arrayMatrix2d03,arrayMatrix2d03))

nan이 포함되지 않은 배열 비교
 [[ True  True  True  True  True]
 [ True  True  True  True  True]]
nan이 포함되지 않은 배열 비교
 True
nan이 포함된 배열 비교
 [[ True  True False  True  True]
 [ True  True  True  True  True]]
nan이 포함된 배열 비교
 False


In [ ]:
print("0보다 작은 값의 불리언 인덱스 : \n", arrayMatrix2d03 < 0)
print("0보다 작은 값 : \n", arrayMatrix2d03[arrayMatrix2d03 < 0])

print("0보다 작은 값의 인덱스 :\n",np.where(arrayMatrix2d03 < 0))    
print("0보다 작은 값 :\n", arrayMatrix2d03[np.where(arrayMatrix2d03 < 0)])

0보다 작은 값의 불리언 인덱스 : 
 [[ True  True False False False]
 [False False False False False]]
0보다 작은 값 : 
 [ -2. -inf]
0보다 작은 값의 인덱스 :
 (array([0, 0]), array([0, 1]))
0보다 작은 값 :
 [ -2. -inf]
