<a href="https://colab.research.google.com/github/yongjaeahn/python_coding/blob/main/korean/source/06_05_%EB%A6%AC%EC%8A%A4%ED%8A%B8%EC%99%80_numpy_%EB%B0%B0%EC%97%B4_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

	리스트와 numpy 배열 데이터 분석

최대값/최소값

In [ ]:
import numpy as np

list_vector = [10,9,8,7,6,5,4,3,2,1]
print("list_vector의 최소값 : ", min(list_vector))
print("list_vector의 최대값 : ", max(list_vector))

array_vector = np.array(list_vector)
print("array_vector의 최소값 : ", min(array_vector))
print("array_vector의 최대값 : ", max(array_vector))

list_vector의 최소값 :  1
list_vector의 최대값 :  10
array_vector의 최소값 :  1
array_vector의 최대값 :  10


In [ ]:
import numpy as np

array_matrix = np.arange(1,51).reshape(5,10)
print("array_matrix :\n",array_matrix)
print("최소값 : ", np.min(array_matrix))
print("최대값 : ", np.max(array_matrix))
print("열의 최소값 : ", np.min(array_matrix,axis=0))
print("열의 최대값 : ", np.max(array_matrix,axis=0))
print("행의 최소값 : ", np.min(array_matrix,axis=1))
print("행의 최대값 : ", np.max(array_matrix,axis=1))

array_matrix :
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
최소값 :  1
최대값 :  50
열의 최소값 :  [ 1  2  3  4  5  6  7  8  9 10]
열의 최대값 :  [41 42 43 44 45 46 47 48 49 50]
행의 최소값 :  [ 1 11 21 31 41]
행의 최대값 :  [10 20 30 40 50]


In [ ]:
import numpy as np

array_vector = np.array([10,9,8,7,6,5,4,3,2,1])
min_index = np.argmin(array_vector)
print("최소값 인덱스 :", min_index)
print("최소값 : ", array_vector[min_index])
max_index = np.argmax(array_vector)
print("최대값 인덱스 :", max_index)
print("최대값 : ", array_vector[max_index])
#최대값을 국외자로 가정하고 평균값으로 변경
array_vector[max_index] = np.mean(array_vector)
print("변경후 array_vector :",array_vector)

최소값 인덱스 : 9
최소값 :  1
최대값 인덱스 : 0
최대값 :  10
변경후 array_vector : [5 9 8 7 6 5 4 3 2 1]


합과 곱

In [ ]:
import numpy as np

array_matrix = np.arange(1,51).reshape(5,10)
print("array_matrix :\n",array_matrix)
print("array_matrix의 합 :",np.sum(array_matrix))
print("array_matrix의 곱 :",np.prod(array_matrix))

array_matrix :
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
array_matrix의 합 : 1275
array_matrix의 곱 : -3258495067890909184


In [ ]:
array_matrix = np.arange(1,51).reshape(5,10)
array_matrix = array_matrix.astype(np.float_)
print("array_matrix의 합 :",np.sum(array_matrix))
print("array_matrix의 곱 :",np.prod(array_matrix))

array_matrix의 합 : 1275.0
array_matrix의 곱 : 3.0414093201713376e+64


In [ ]:
array_matrix = np.array([[9,2,7],[1,7,5]])
print("array_matrix의 합 :",np.sum(array_matrix))
print("array_matrix의 곱 :",np.prod(array_matrix))

array_matrix의 합 : 31
array_matrix의 곱 : 4410


In [ ]:
print(np.shape(array_matrix))
print(array_matrix.shape)

(2, 3)
(2, 3)


In [ ]:
array_matrix = np.arange(1,51,dtype=np.float_).reshape(5,10)
print(array_matrix.dtype)

float64


누적합과 누적곱

In [ ]:
array_matrix = np.array([[9,2,7],[1,7,5]])
print("array_matrix의 누적합 : ",np.cumsum(array_matrix))
print("array_matrix의 누적곱 : ",np.cumprod(array_matrix))

array_matrix의 누적합 :  [ 9 11 18 19 26 31]
array_matrix의 누적곱 :  [   9   18  126  126  882 4410]


In [ ]:
print(array_matrix.reshape(-1))

[9 2 7 1 7 5]


In [ ]:
print("array_matrix :\n", array_matrix)
print("array_matrix의 열 누적합 : \n",np.cumsum(array_matrix,axis=0))
print("array_matrix의 행 누적합 : \n",np.cumsum(array_matrix,axis=1))
print("array_matrix의 열 누적곱 : \n",np.cumprod(array_matrix,axis=0))
print("array_matrix의 행 누적곱 : \n",np.cumprod(array_matrix,axis=1))

array_matrix :
 [[9 2 7]
 [1 7 5]]
array_matrix의 열 누적합 : 
 [[ 9  2  7]
 [10  9 12]]
array_matrix의 행 누적합 : 
 [[ 9 11 18]
 [ 1  8 13]]
array_matrix의 열 누적곱 : 
 [[ 9  2  7]
 [ 9 14 35]]
array_matrix의 행 누적곱 : 
 [[  9  18 126]
 [  1   7  35]]


In [ ]:
import numpy as np

list_vector = [10,8,6,4,2]
print("list_vector의 누적합 : ",np.cumsum(np.array(list_vector)))
print("list_vector의 누적곱 : ",np.cumprod(np.array(list_vector)))

list_vector의 누적합 :  [10 18 24 28 30]
list_vector의 누적곱 :  [  10   80  480 1920 3840]


차이

In [ ]:
import numpy as np

array_vector = np.array([10,9,8,7,6,5,4,3,2,1])
array_matrix = np.array([[9,2,7],[1,7,5],[3,5,3]])

print("array_vector의 차이 :",np.diff(array_vector))
print("array_matrix의 차이 (2차원) :\n",np.diff(array_matrix))
print("array_matrix 열의 차이 :\n",np.diff(array_matrix,axis=0))
print("array_matrix 행의 차이 :\n",np.diff(array_matrix,axis=1))
print("array_matrix의 차이 (1차원) :",np.diff(array_matrix.reshape(-1)))

array_vector의 차이 : [-1 -1 -1 -1 -1 -1 -1 -1 -1]
array_matrix의 차이 (2차원) :
 [[-7  5]
 [ 6 -2]
 [ 2 -2]]
array_matrix 열의 차이 :
 [[-8  5 -2]
 [ 2 -2 -2]]
array_matrix 행의 차이 :
 [[-7  5]
 [ 6 -2]
 [ 2 -2]]
array_matrix의 차이 (1차원) : [-7  5 -6  6 -2 -2  2 -2]


통계

In [ ]:
import numpy as np

array_vector = np.array([10,9,8,7,98,6,5,4,3,2,1])
array_matrix = np.array([[9,2,7],[1,7,5],[3,5,3]])

print("array_vector의 평균 :",np.mean(array_vector))
print("array_matrix의 평균 :",np.mean(array_matrix))
print("array_matrix 열의 평균 :",np.mean(array_matrix,axis=0))
print("array_matrix 행의 평균 :",np.mean(array_matrix,axis=1))

array_vector의 평균 : 13.909090909090908
array_matrix의 평균 : 4.666666666666667
array_matrix 열의 평균 : [4.33333333 4.66666667 5.        ]
array_matrix 행의 평균 : [6.         4.33333333 3.66666667]


In [ ]:
import numpy as np

array_vector = np.array([10,9,8,7,98,6,5,4,3,2,1])
temp_array_vector = array_vector[array_vector != np.max(array_vector)]
print("최대값 이상치가 제거된 array_vector :",temp_array_vector)
print("array_vector의 평균 :",np.mean(temp_array_vector))

최대값 이상치가 제거된 array_vector : [10  9  8  7  6  5  4  3  2  1]
array_vector의 평균 : 5.5


In [ ]:
import numpy as np

array_vector = np.array([10,9,8,7,6,6,5,4,3,2,1])
array_matrix = np.array([[9,2,7],[1,7,5],[3,5,3]])

print("array_vector의 최빈치 :",np.mode(array_vector))
print("array_matrix의 최빈치 :",np.mode(array_matrix))
print("array_matrix 열의 최빈치 :\n",np.mode(array_matrix,axis=0))
print("array_matrix 행의 최빈치 :\n",np.mode(array_matrix,axis=1))

AttributeError: ignored

In [2]:
import numpy as np
from scipy import stats

array_vector = np.array([10,9,8,7,6,6,5,4,3,2,1])
array_matrix = np.array([[9,9,2,3],[9,7,7,5],[3,5,2,3]])

print("array_vector의 최빈치 :",stats.mode(array_vector))
print("array_matrix :\n",array_matrix)
print("array_matrix의 최빈치 (2차원) :\n",stats.mode(array_matrix))
print("array_matrix 열의 최빈치 :\n",stats.mode(array_matrix,axis=0))
print("array_matrix 행의 최빈치 :\n",stats.mode(array_matrix,axis=1))

array_vector의 최빈치 : ModeResult(mode=6, count=2)
array_matrix :
 [[9 9 2 3]
 [9 7 7 5]
 [3 5 2 3]]
array_matrix의 최빈치 (2차원) :
 ModeResult(mode=array([9, 5, 2, 3]), count=array([2, 1, 2, 2]))
array_matrix 열의 최빈치 :
 ModeResult(mode=array([9, 5, 2, 3]), count=array([2, 1, 2, 2]))
array_matrix 행의 최빈치 :
 ModeResult(mode=array([9, 7, 3]), count=array([2, 2, 2]))


In [ ]:
print("array_vector의 최빈치 :",stats.mode(array_vector).mode)
print("array_vector의 최빈치 발생 횟수 :",stats.mode(array_vector).count)
print("array_matrix 1열의 최빈치 :",stats.mode(array_matrix,axis=0).mode[0])
print("array_matrix 1열의 최빈치 발생 횟수 :",stats.mode(array_matrix,axis=0).count[0])
print("array_matrix 2행의 최빈치 :",stats.mode(array_matrix,axis=1).mode[1])
print("array_matrix 2행의 최빈치 발생 횟수 :",stats.mode(array_matrix,axis=1).count[1])

array_vector의 최빈치 : 6
array_vector의 최빈치 발생 횟수 : 2
array_matrix 1열의 최빈치 : 9
array_matrix 1열의 최빈치 발생 횟수 : 2
array_matrix 2행의 최빈치 : 7
array_matrix 2행의 최빈치 발생 횟수 : 2


In [4]:
array_vector = np.array([10,9,8,7,6,6,5,4,3,3,2,1])

print("array_vector의 최빈치 :",stats.mode(array_vector))

array_vector의 최빈치 : ModeResult(mode=3, count=2)


In [ ]:
import scipy
print(scipy.__version__)

1.11.4
