<a href="https://colab.research.google.com/github/yongjaeahn/python_coding/blob/main/korean/source/06_03_%EB%A6%AC%EC%8A%A4%ED%8A%B8%EC%99%80_numpy_%EB%B0%B0%EC%97%B4_%EB%8B%A4%EB%A3%A8%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

	리스트와 numpy 배열 다루기

형상 확인

In [ ]:
import numpy as np

list_vector = [1,2,3,4,5]
array_vector = np.arange(1,6)
print("array_vector :", array_vector)

print("len(list_vector)  :", len(list_vector))
print("len(array_vector) :", len(array_vector))

array_vector : [1 2 3 4 5]
len(list_vector)  : 5
len(array_vector) : 5


In [ ]:
import numpy as np

list_matrix = [[1,2,3],[4,5,6]]
array_matrix = np.arange(1,7).reshape(2,3)
print("array_matrix :\n", array_matrix)

print("np.ndim(list_matrix) :", np.ndim(list_matrix))
print("np.ndim(array_matrix) :", np.ndim(array_matrix))
print("np.size(list_matrix) :", np.size(list_matrix))
print("np.size(array_matrix) :", np.size(array_matrix))
print("np.shape(list_matrix) :", np.shape(list_matrix))
print("np.shape(array_matrix) :", np.shape(array_matrix))

array_matrix :
 [[1 2 3]
 [4 5 6]]
np.ndim(list_matrix) : 2
np.ndim(array_matrix) : 2
np.size(list_matrix) : 6
np.size(array_matrix) : 6
np.shape(list_matrix) : (2, 3)
np.shape(array_matrix) : (2, 3)


In [ ]:
import numpy as np

array_matrix = np.arange(1,7).reshape(2,3)
print("array_matrix :\n", array_matrix)

print("array_matrix.ndim :", array_matrix.ndim)
print("array_matrix.size :", array_matrix.size)
print("array_matrix.shape :", array_matrix.shape)

array_matrix :
 [[1 2 3]
 [4 5 6]]
array_matrix.ndim : 2
array_matrix.size : 6
array_matrix.shape : (2, 3)


조회

In [ ]:
import numpy as np

list_vector = [1,2,3,4,5,6,7,8,9,10]
array_vector = np.array(list_vector)

print("2~8번째 요소 중 짝수번째 요소 : ", list_vector[1:8:2], array_vector[1:8:2])
print("마지막에서 2~8번째 요소 중 짝수번째 요소 :",
      list_vector[-2:-9:-2], array_vector[-2:-9:-2])
print("3~7번째 요소 :", list_vector[2:7], array_vector[2:7])
print("1~7번째 요소 :", list_vector[:7], array_vector[:7])
print("7번째~마지막 요소 :", list_vector[6:], array_vector[6:])
print("전체 요소 중 홀수번째 요소 :",list_vector[::2], array_vector[::2])

3~7번째 요소 : [3, 4, 5, 6, 7] [3 4 5 6 7]
1~7번째 요소 : [1, 2, 3, 4, 5, 6, 7] [1 2 3 4 5 6 7]
7번째~마지막 요소 : [7, 8, 9, 10] [ 7  8  9 10]
2~8번째 요소 중 짝수번째 요소 :  [2, 4, 6, 8] [2 4 6 8]
마지막에서 2~8번째 요소 중 짝수번째 요소 : [9, 7, 5, 3] [9 7 5 3]
전체 요소 중 홀수번째 요소 : [1, 3, 5, 7, 9] [1 3 5 7 9]


In [ ]:
sample_string = "긴 문자열입니다."
print(sample_string[2:5])

문자열


In [ ]:
import numpy as np

list_matrix = [[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20],
               [21,22,23,24,25]]
array_matrix = np.array(list_matrix)
print("array_matrix :\n", array_matrix)

print("첫 요소 :", list_matrix[0][0], array_matrix[0][0], array_matrix[0,0])
print("2행 3열 요소 :", list_matrix[1][2], array_matrix[1][2], array_matrix[1,2])
print("마지막 요소 :", list_matrix[-1][-1], array_matrix[-1][-1], array_matrix[-1,-1])

array_matrix :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
첫 요소 : 1 1 1
2행 3열 요소 : 8 8 8
마지막 요소 : 25 25 25


In [ ]:
print("1행벡터 :", list_matrix[0], array_matrix[0])
print("3행벡터 :", list_matrix[2][:], array_matrix[2][:])
print("2~4행벡터(리스트) :", list_matrix[1:4])
print("2~4행벡터(배열) :\n", array_matrix[1:4,:])

1행벡터 : [1, 2, 3, 4, 5] [1 2 3 4 5]
3행벡터 : [11, 12, 13, 14, 15] [11 12 13 14 15]
2~4행벡터(리스트) : [[6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
2~4행벡터(배열) :
 [[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
print("1열벡터 :", list_matrix[:][0], array_matrix[:][0])
print("3열벡터 :", list_matrix[:][2], array_matrix[:][2])
print("2~4열벡터(리스트) :", list_matrix[:][1:4])
print("2~4열벡터(배열) :\n", array_matrix[:][1:4])

1열벡터 : [1, 2, 3, 4, 5] [1 2 3 4 5]
3열벡터 : [11, 12, 13, 14, 15] [11 12 13 14 15]
2~4열벡터(리스트) : [[6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
2~4열벡터(배열) :
 [[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
print("array_matrix :\n", array_matrix)
print("1열벡터 :", array_matrix[:,0])
print("3열벡터 :", array_matrix[:,2])
print("2~4열벡터(배열) :\n", array_matrix[:,1:4])

array_matrix :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
1열벡터 : [ 1  6 11 16 21]
3열벡터 : [ 3  8 13 18 23]
2~4열벡터(배열) :
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]


In [ ]:
print("2~3 행 슬라이싱(1:3) + 2~4 열 슬라이싱(1:4) :\n", array_matrix[1:3,1:4])

2~3 행 슬라이싱(1:3) + 2~4 열 슬라이싱(1:4) :
 [[ 7  8  9]
 [12 13 14]]


In [ ]:
array_vector = np.array([1,2,3,4,5])
print("첫번째 요소 :", array_vector[0])
print("세번째 요소 :", array_vector[2])
print("마지막 요소 :", array_vector[-1])

첫번째 요소 : 1
세번째 요소 : 3
마지막 요소 : 5


In [ ]:
print("array_vector[[0,2,-1]] :", array_vector[[0,2,-1]])

array_vector[[0,2,-1]] : [1 3 5]


In [ ]:
array_matrix = np.array([[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20],
               [21,22,23,24,25]])

print("array_matrix[[0,2,-1],[0,2,-1]] : ", array_matrix[[0,2,-1],[0,2,-1]])

array_matrix[[0,2,-1],[0,2,-1]] :  [ 1 13 25]


In [ ]:
print("2행과 4행 :\n", array_matrix[[1,3]])

2행과 4행 :
 [[ 6  7  8  9 10]
 [16 17 18 19 20]]


In [ ]:
print("2열과 4열 :\n", array_matrix[:,[1,3]])

2열과 4열 :
 [[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]
 [22 24]]


In [ ]:
array_matrix < 10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [ ]:
print(array_matrix[array_matrix < 10])

mask = array_matrix < 10
print(array_matrix[mask])

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
mask = (array_matrix < 10) | (array_matrix > 20)
print(array_matrix[mask])

[ 1  2  3  4  5  6  7  8  9 21 22 23 24 25]


In [ ]:
import numpy as np

employee_list = [320811, "안용제", "010-1234-5678", "서울시 영등포구 당산동", 99.5]
print("리스트(list) : ", employee_list)

employee_array = np.array([320811, "안용제", "010-1234-5678", "서울시 영등포구 당산동", 99.5])
print("배열(array) : ", employee_array)

리스트(list) :  [320811, '안용제', '010-1234-5678', '서울시 영등포구 당산동', 99.5]
배열(array) :  ['320811' '안용제' '010-1234-5678' '서울시 영등포구 당산동' '99.5']


수정

In [ ]:
list_matrix = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]

print("list_matrix (수정전):\n", list_matrix)
list_matrix[0][0] = -999
print("list_matrix (수정후):\n", list_matrix)

list_matrix (수정전):
 [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
list_matrix (수정후):
 [[-999, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]


In [ ]:
import numpy as np

array_matrix = np.arange(1,26).reshape(5,5)

print("array_matrix (수정전) :\n", array_matrix)
array_matrix[1][2] = -888
array_matrix[-1,-1] = -777
print("array_matrix (수정후):\n", array_matrix)

array_matrix (수정전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
array_matrix (수정후):
 [[   1    2    3    4    5]
 [   6    7 -888    9   10]
 [  11   12   13   14   15]
 [  16   17   18   19   20]
 [  21   22   23   24 -777]]


In [ ]:
array_matrix[0] = 1
array_matrix[2:3,:] = -1
print("array_matrix (수정후):\n", array_matrix)

array_matrix (수정후):
 [[   1    1    1    1    1]
 [   6    7 -888    9   10]
 [  -1   -1   -1   -1   -1]
 [  16   17   18   19   20]
 [  21   22   23   24 -777]]


In [ ]:
array_matrix[:,0] = 2
array_matrix[:,2:3] = -2
print("array_matrix (수정후):\n", array_matrix)

array_matrix (수정후):
 [[   2    1   -2    1    1]
 [   2    7   -2    9   10]
 [   2   -1   -2   -1   -1]
 [   2   17   -2   19   20]
 [   2   22   -2   24 -777]]


In [ ]:
array_matrix[1:3,1:4] = 100
print("array_matrix (수정후):\n", array_matrix)

array_matrix (수정후):
 [[   2    1   -2    1    1]
 [   2  100  100  100   10]
 [   2  100  100  100   -1]
 [   2   17   -2   19   20]
 [   2   22   -2   24 -777]]


In [ ]:
array_matrix[[0,0,0,-1,-1,-1],[0,1,2,-1,-2,-3]] = -100
print("array_matrix (수정후):\n", array_matrix)

array_matrix (수정후):
 [[-100 -100 -100    1    1]
 [   2  100  100  100   10]
 [   2  100  100  100   -1]
 [   2   17   -2   19   20]
 [   2   22 -100 -100 -100]]


In [ ]:
mask = array_matrix == -100
array_matrix[mask] = 100
print("array_matrix (수정후):\n", array_matrix)

array_matrix (수정후):
 [[100 100 100   1   1]
 [  2 100 100 100  10]
 [  2 100 100 100  -1]
 [  2  17  -2  19  20]
 [  2  22 100 100 100]]


삭제

In [ ]:
list_vector = [1,2,3,4,5,6,7,8,9,10]
print("list_vector (삭제전): ", list_vector)
del list_vector[3]     # 인덱스로 삭제
print("list_vector (인덱스 3 즉 4번째 요소 삭제후): ", list_vector)
list_vector.remove(10) #  값으로 삭제
print("list_vector (값 10으로 삭제후): ", list_vector)

list_vector (삭제전):  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
list_vector (인덱스 3 즉 4번째 요소 삭제후):  [1, 2, 3, 5, 6, 7, 8, 9, 10]
list_vector (값 10으로 삭제후):  [1, 2, 3, 5, 6, 7, 8, 9]


In [ ]:
import numpy as np

array_matrix = np.arange(1,26).reshape(5,5)
print("array_matrix (삭제전) :\n", array_matrix)
array_matrix = np.delete(array_matrix,1,axis=0)
print("array_matrix (인덱스 1 즉 2행 삭제후) :\n", array_matrix)
array_matrix = np.delete(array_matrix,[1,3],axis=1)
print("array_matrix (인덱스 1과 3 즉 2열과 4열 삭제후) :\n", array_matrix)

array_matrix (삭제전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
array_matrix (인덱스 1 즉 2행 삭제후) :
 [[ 1  2  3  4  5]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
array_matrix (인덱스 1과 3 즉 2열과 4열 삭제후) :
 [[ 1  3  5]
 [11 13 15]
 [16 18 20]
 [21 23 25]]


추가

In [ ]:
list_vector = [1,2,4,5]
print("list_vector 추가전 :", list_vector)
list_vector.append(6)
print("6을 확장한 후 :", list_vector)
list_vector.insert(2,3)
print("3을 삽입한 후 :", list_vector)
list_vector.extend([7,8])
print("[7,8] 리스트를 확장한 후 :", list_vector)
list_vector = [-1,0] + list_vector + [9,10]
print("[-1,0]와 [9~10] 리스트를 앞뒤로 이어붙인 후 :",list_vector)

list_vector 추가전 : [1, 2, 4, 5]
6을 확장한 후 : [1, 2, 4, 5, 6]
3을 삽입한 후 : [1, 2, 3, 4, 5, 6]
[7,8] 리스트를 확장한 후 : [1, 2, 3, 4, 5, 6, 7, 8]
[-1,0]와 [9~10] 리스트를 앞뒤로 이어붙인 후 : [-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
import numpy as np
array_matrix = np.arange(1,26).reshape(5,5)
print("array_matrix (추가전) :\n", array_matrix)
new_row_2d = np.array([[26,27,28,29,30],[31,32,33,34,35]])
print("신규행 :\n", new_row_2d)
array_matrix = np.append(array_matrix,new_row_2d,axis=0)
print("array_matrix (신규행 추가후) :\n", array_matrix)

array_matrix (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
신규행 :
 [[26 27 28 29 30]
 [31 32 33 34 35]]
array_matrix (신규행 추가후) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [ ]:
import numpy as np
array_matrix = np.arange(1,26).reshape(5,5)
print("array_matrix (추가전) :\n", array_matrix)
new_column_2d = np.array([[26],[27],[28],[29],[30]])
print("신규열 :\n", new_column_2d)
array_matrix = np.append(array_matrix,new_column_2d,axis=1)
print("array_matrix (신규열 추가후) :\n", array_matrix)

array_matrix (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
신규열 :
 [[26]
 [27]
 [28]
 [29]
 [30]]
array_matrix (신규열 추가후) :
 [[ 1  2  3  4  5 26]
 [ 6  7  8  9 10 27]
 [11 12 13 14 15 28]
 [16 17 18 19 20 29]
 [21 22 23 24 25 30]]


In [ ]:
import numpy as np

array_matrix = np.arange(1,26).reshape(5,5)
print("array_matrix (추가전) :\n", array_matrix)
new_row_2d = np.array([[26,27,28,29,30],[31,32,33,34,35]])
print("신규열(행표현) :\n", new_row_2d)
new_column_2d = np.transpose(new_row_2d)
print("신규열 :\n", new_column_2d)

array_matrix (추가전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
신규열(행표현) :
 [[26 27 28 29 30]
 [31 32 33 34 35]]
신규열 :
 [[26 31]
 [27 32]
 [28 33]
 [29 34]
 [30 35]]


In [ ]:
array_matrix = np.append(array_matrix,new_column_2d,axis=1)
print("array_matrix (신규열 추가후) :\n", array_matrix)

array_matrix (신규열 추가후) :
 [[ 1  2  3  4  5 26 31]
 [ 6  7  8  9 10 27 32]
 [11 12 13 14 15 28 33]
 [16 17 18 19 20 29 34]
 [21 22 23 24 25 30 35]]


In [ ]:
input_data = [1,2,3]      # 데이터 저장소에서 읽어 왔다고 가정
list_vector = []          # 빈 리스트
print("list_vector (빈 리스트) :\n", list_vector)

for datum in input_data:
  list_vector.append(datum)

print("list_vector (값을 읽어와 생성한 리스트) :\n", list_vector)

list_vector (빈 리스트) :
 []
list_vector (값을 읽어와 생성한 리스트) :
 [1, 2, 3]


In [ ]:
import numpy as np

# 데이터 저장소에서 읽어 왔다고 가정
row = 3
column = 3
input_data = [[1,2,3],[4,5,6],[7,8,9]]

array_matrix = np.empty(shape=(row, column))
print("array_matrix (빈 배열) :\n", array_matrix)

for i in range(row):
  for j in range(column):
    array_matrix[i,j] = input_data[i][j]

print("array_matrix (값을 읽어와 생성한 배열) :\n", array_matrix)

array_matrix (빈 배열) :
 [[4.90825189e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]
array_matrix (값을 읽어와 생성한 배열) :
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


numpy 기타

In [ ]:
import numpy as np

array_matrix = np.arange(1,26).reshape(5,5)
print("array_matrix (변경전) :\n", array_matrix)
array_matrix = np.flipud(array_matrix)
print("array_matrix (행렬의 상하 변경후) :\n", array_matrix)

array_matrix (변경전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
array_matrix (행렬의 상하 변경후) :
 [[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [ ]:
import numpy as np

array_matrix = np.arange(1,26).reshape(5,5)
print("array_matrix (변경전) :\n", array_matrix)
array_matrix = np.roll(array_matrix,shift=3)
print("array_matrix (행렬을 굴린 후) :\n", array_matrix)

array_matrix (변경전) :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
array_matrix (행렬을 굴린 후) :
 [[23 24 25  1  2]
 [ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]]


In [ ]:
import numpy as np

array_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("array_matrix (회전전) :\n", array_matrix)
array_matrix = np.rot90(array_matrix,k=1)
print("array_matrix (시계 반대방향 90도 회전후) :\n", array_matrix)
array_matrix = np.rot90(array_matrix,k=-2)
print("array_matrix (시계 방향 180도 회전후) :\n", array_matrix)

array_matrix (회전전) :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array_matrix (시계 반대방향 90도 회전후) :
 [[3 6 9]
 [2 5 8]
 [1 4 7]]
array_matrix (시계 방향 180도 회전후) :
 [[7 4 1]
 [8 5 2]
 [9 6 3]]


In [ ]:
import numpy as np

array_matrix = np.array([[1,2],[3,4]])
print("array_matrix (반복전) :\n", array_matrix)
array_matrix = np.tile(array_matrix, reps=3)
print("array_matrix (3열로 반복후) :\n", array_matrix)

array_matrix = np.array([[1,2],[3,4]])
array_matrix = np.tile(array_matrix, reps=(2,3))
print("array_matrix (2행 3열로 반복후) :\n", array_matrix)

array_matrix (반복전) :
 [[1 2]
 [3 4]]
array_matrix (3열로 반복후) :
 [[1 2 1 2 1 2]
 [3 4 3 4 3 4]]
array_matrix (2행 3열로 반복후) :
 [[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [ ]:
import numpy as np

array_vector = np.arange(10)
print("array_vector (섞기전) :\n", array_vector)
np.random.shuffle(array_vector)
print("array_vector (섞은후) :\n", array_vector)

array_vector (섞기전) :
 [0 1 2 3 4 5 6 7 8 9]
array_vector (섞은후) :
 [3 0 7 1 9 6 5 4 2 8]


In [ ]:
import numpy as np

array_matrix = np.arange(1,31).reshape(6,5)
print("array_matrix :\n", array_matrix)

splited_matrix = np.split(array_matrix, 2, axis=0)
print("splited_matrix[0] :\n", splited_matrix[0])
print("splited_matrix[1] :\n", splited_matrix[1])

array_matrix :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
splited_matrix[0] :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
splited_matrix[1] :
 [[16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [ ]:
splited_matrix = np.split(array_matrix, (1,3), axis=0)
print("splited_matrix[0] :\n", splited_matrix[0])
print("splited_matrix[1] :\n", splited_matrix[1])
print("splited_matrix[2] :\n", splited_matrix[2])

splited_matrix[0] :
 [[1 2 3 4 5]]
splited_matrix[1] :
 [[ 6  7  8  9 10]
 [11 12 13 14 15]]
splited_matrix[2] :
 [[16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [ ]:
import numpy as np

array_vector = np.array([1,2,3,4,5])
print("array_vector :\n", array_vector)
print("0보다 작은 값이 있는지 확인 :",np.any(array_vector < 0))

array_matrix = np.array([[-2,-1,0,1,2],[1,2,3,4,5]])
print("array_matrix :\n", array_matrix)
print("0보다 작은 값이 있는지 확인 :",np.any(array_matrix < 0))

array_vector :
 [1 2 3 4 5]
0보다 작은 값이 있는지 확인 : False
array_matrix :
 [[-2 -1  0  1  2]
 [ 1  2  3  4  5]]
0보다 작은 값이 있는지 확인 : True


In [ ]:
equal_boolean_idx = np.array([1,2,3]) == np.array([-1,2,-3])
print("nan인지 확인하는 불리언 인덱스 : ",equal_boolean_idx)
print("같은 값이 하나라도 있는지 확인 :",np.any(equal_boolean_idx))

nan인지 확인하는 불리언 인덱스 :  [False  True False]
같은 값이 하나라도 있는지 확인 : True


In [ ]:
import numpy as np

array_matrix01 = np.array([[-2,-1,0,1,2],[1,2,3,4,5]])
array_matrix02 = np.array([[1,0,0,0,1],[5,4,3,2,1]])
array_matrix03 = array_matrix01 / array_matrix02
print("나눗셈 결과 행렬 : \n", array_matrix03)

print("nan인지 확인하는 불리언 인덱스 : \n", np.isnan(array_matrix03))

나눗셈 결과 행렬 : 
 [[-2.  -inf  nan  inf  2. ]
 [ 0.2  0.5  1.   2.   5. ]]
nan인지 확인하는 불리언 인덱스 : 
 [[False False  True False False]
 [False False False False False]]


<ipython-input-7-d6836f2b8ce7>:5: RuntimeWarning: divide by zero encountered in divide
  array_matrix03 = array_matrix01 / array_matrix02
<ipython-input-7-d6836f2b8ce7>:5: RuntimeWarning: invalid value encountered in divide
  array_matrix03 = array_matrix01 / array_matrix02


In [ ]:
print("배열 비교\n",array_matrix02 == array_matrix02)
print("배열 비교\n",np.array_equal(array_matrix02,array_matrix02))

print("nan이 포함된 배열 비교\n",array_matrix03 == array_matrix03)
print("nan이 포함된 배열 비교\n",np.array_equal(array_matrix03,array_matrix03))

배열 비교
 [[ True  True  True  True  True]
 [ True  True  True  True  True]]
배열 비교
 True
nan이 포함된 배열 비교
 [[ True  True False  True  True]
 [ True  True  True  True  True]]
nan이 포함된 배열 비교
 False


In [ ]:
print("nan인 값을 0으로 바꾼 행렬 :\n",
      np.where(np.isnan(array_matrix03), 0, array_matrix03))
print("유한하지 않은 값을 0으로 바꾼 행렬 :\n",
      np.where(~np.isfinite(array_matrix03), 0, array_matrix03))

nan인 값을 0으로 바꾼 행렬 :
 [[-2.  -inf  0.   inf  2. ]
 [ 0.2  0.5  1.   2.   5. ]]
유한하지 않은 값을 0으로 바꾼 행렬 :
 [[-2.   0.   0.   0.   2. ]
 [ 0.2  0.5  1.   2.   5. ]]


In [ ]:
print("0보다 작은 값의 불리언 인덱스 : \n", array_matrix03 < 0)
print("0보다 작은 값 : \n", array_matrix03[array_matrix03 < 0])

print("0보다 작은 값의 인덱스 :\n",np.where(array_matrix03 < 0))
print("0보다 작은 값 :\n", array_matrix03[np.where(array_matrix03 < 0)])

0보다 작은 값의 불리언 인덱스 : 
 [[ True  True False False False]
 [False False False False False]]
0보다 작은 값 : 
 [ -2. -inf]
0보다 작은 값의 인덱스 :
 (array([0, 0]), array([0, 1]))
0보다 작은 값 :
 [ -2. -inf]
