<a href="https://colab.research.google.com/github/yongjaeahn/PythonCoding/blob/main/korean/source/10_%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5_%EC%BD%94%EB%94%A9_%EB%A7%9B%EB%B3%B4%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

	선형 회귀 알고리즘

데이터 수집

In [4]:
from sklearn.datasets import load_diabetes

diabetes = load_diabetes()

print(type(diabetes))
print(dir(diabetes))

<class 'sklearn.utils._bunch.Bunch'>
['DESCR', 'data', 'data_filename', 'data_module', 'feature_names', 'frame', 'target', 'target_filename']


In [ ]:
print(diabetes.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, total serum cholesterol
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, total cholesterol / HDL
      - s5      ltg, possibly log of serum triglycerides level
      - s6      glu, blood sugar level

Note: Each of these 1

In [ ]:
help(load_diabetes)

Help on function load_diabetes in module sklearn.datasets._base:

load_diabetes(*, return_X_y=False, as_frame=False, scaled=True)
    Load and return the diabetes dataset (regression).
    
    ==============   ==================
    Samples total    442
    Dimensionality   10
    Features         real, -.2 < x < .2
    Targets          integer 25 - 346
    ==============   ==================
    
    .. note::
       The meaning of each feature (i.e. `feature_names`) might be unclear
       (especially for `ltg`) as the documentation of the original dataset is
       not explicit. We provide information that seems correct in regard with
       the scientific literature in this field of research.
    
    Read more in the :ref:`User Guide <diabetes_dataset>`.
    
    Parameters
    ----------
    return_X_y : bool, default=False
        If True, returns ``(data, target)`` instead of a Bunch object.
        See below for more information about the `data` and `target` object.
    
    

데이터 전처리

In [ ]:
print(diabetes.feature_names)

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']


In [ ]:
print(diabetes.data[0:3])
print(diabetes.data[-1:-3:-1])

[[ 0.03807591  0.05068012  0.06169621  0.02187239 -0.0442235  -0.03482076
  -0.04340085 -0.00259226  0.01990749 -0.01764613]
 [-0.00188202 -0.04464164 -0.05147406 -0.02632753 -0.00844872 -0.01916334
   0.07441156 -0.03949338 -0.06833155 -0.09220405]
 [ 0.08529891  0.05068012  0.04445121 -0.00567042 -0.04559945 -0.03419447
  -0.03235593 -0.00259226  0.00286131 -0.02593034]]
[[-0.04547248 -0.04464164 -0.0730303  -0.08141314  0.08374012  0.02780893
   0.17381578 -0.03949338 -0.00422151  0.00306441]
 [-0.04547248 -0.04464164  0.03906215  0.00121528  0.01631843  0.01528299
  -0.02867429  0.02655962  0.04452873 -0.02593034]]


In [ ]:
print(diabetes.target[0:3])
print(diabetes.target[-1:-3:-1])

[151.  75. 141.]
[ 57. 220.]


In [ ]:
import numpy as np

def normalize(values):
    mean = np.mean(values)    # 평균
    std = np.std(values)      # 표준편차
    # 정규화 = (값 - 평균) / 표준편차
    normalized = (values - mean) / std    

    return normalized

ages = np.array([50,45,20,60,63,57,40,47,30,58])
normalizedAges = normalize(ages)
print('정규화된 나이 :',normalizedAges)

bmis = np.array([30,28,22,28,27,32,27,22,25,29])
normalizedBmis = normalize(bmis)
print('정규화된 체질량 지수 :',normalizedBmis)

정규화된 나이 : [ 0.22834992 -0.15223328 -2.05514926  0.98951631  1.21786623  0.76116639
 -0.53281647  0.         -1.29398287  0.83728303]
정규화된 체질량 지수 : [ 0.97849211  0.32616404 -1.63082018  0.32616404  0.          1.63082018
  0.         -1.63082018 -0.65232807  0.65232807]


In [ ]:
sex = np.array(['M','F','F','M','M','F','F','F','M','F'])
sexNumeric = np.where(sex == 'M',1,0)
print('수치화된 성별 :',sexNumeric)
normalizedSex = normalize(sexNumeric)
print('정규화된 성별 :',normalizedSex)

수치화된 성별 : [1 0 0 1 1 0 0 0 1 0]
정규화된 성별 : [ 1.22474487 -0.81649658 -0.81649658  1.22474487  1.22474487 -0.81649658
 -0.81649658 -0.81649658  1.22474487 -0.81649658]


In [ ]:
from sklearn.preprocessing import StandardScaler

diabetesFeatures = np.array(list(zip(ages,sexNumeric,bmis)))
print('당뇨병 특징 :\n',diabetesFeatures)

scaler = StandardScaler()
normalizedDiabetes = scaler.fit_transform(diabetesFeatures)

print('정규화된 당뇨병 특징 :\n',normalizedDiabetes)

당뇨병 특징 :
 [[50  1 30]
 [45  0 28]
 [20  0 22]
 [60  1 28]
 [63  1 27]
 [57  0 32]
 [40  0 27]
 [47  0 22]
 [30  1 25]
 [58  0 29]]
정규화된 당뇨병 특징 :
 [[ 0.22834992  1.22474487  0.97849211]
 [-0.15223328 -0.81649658  0.32616404]
 [-2.05514926 -0.81649658 -1.63082018]
 [ 0.98951631  1.22474487  0.32616404]
 [ 1.21786623  1.22474487  0.        ]
 [ 0.76116639 -0.81649658  1.63082018]
 [-0.53281647 -0.81649658  0.        ]
 [ 0.         -0.81649658 -1.63082018]
 [-1.29398287  1.22474487 -0.65232807]
 [ 0.83728303 -0.81649658  0.65232807]]


모델 훈련

In [6]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(diabetes.data,diabetes.target)
print('훈련된 회귀방정식의 계수 :',model.coef_)

훈련된 회귀방정식의 계수 : [ -10.0098663  -239.81564367  519.84592005  324.3846455  -792.17563855
  476.73902101  101.04326794  177.06323767  751.27369956   67.62669218]


10

모델 테스트

In [ ]:
print('1년 후 당뇨병 진행의 정량적 측정치 예측을 위한 10개의 독립변수 :\n', diabetes.data[0:3])
yPrediction = model.predict(diabetes.data[0:3])

print('회귀분석 모델로 예측한 1년 후 당뇨병 진행의 정량적 측정치:', yPrediction)
print('회귀분석 모델에 사용된 1년 후 당뇨병 진행의 정량적 측정치:', diabetes.target[0:3])

1년 후 당뇨병 진행의 정량적 측정치 예측을 위한 10개의 독립변수 :
 [[ 0.03807591  0.05068012  0.06169621  0.02187239 -0.0442235  -0.03482076
  -0.04340085 -0.00259226  0.01990749 -0.01764613]
 [-0.00188202 -0.04464164 -0.05147406 -0.02632753 -0.00844872 -0.01916334
   0.07441156 -0.03949338 -0.06833155 -0.09220405]
 [ 0.08529891  0.05068012  0.04445121 -0.00567042 -0.04559945 -0.03419447
  -0.03235593 -0.00259226  0.00286131 -0.02593034]]
회귀분석 모델로 예측한 1년 후 당뇨병 진행의 정량적 측정치: [206.11667725  68.07103297 176.88279035]
회귀분석 모델에 사용된 1년 후 당뇨병 진행의 정량적 측정치: [151.  75. 141.]


In [10]:
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression

# 데이터 수집 및 전처리
diabetes = load_diabetes()

# 모델 훈련
model = LinearRegression()
model.fit(diabetes.data,diabetes.target)

# 모델 테스트
yPrediction = model.predict(diabetes.data[0:3])
print('회귀분석 모델로 예측한 1년 후 당뇨병 진행의 정량적 측정치:', yPrediction)

회귀분석 모델로 예측한 1년 후 당뇨병 진행의 정량적 측정치: [206.11667725  68.07103297 176.88279035]


In [9]:
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression

# 데이터 수집 및 전처리
diabetes = load_diabetes(as_frame=True)

# 모델 훈련
model = LinearRegression()
model.fit(diabetes.data,diabetes.target)

# 모델 테스트
yPrediction = model.predict(diabetes.data[0:3])
print('회귀분석 모델로 예측한 1년 후 당뇨병 진행의 정량적 측정치:', yPrediction)

회귀분석 모델로 예측한 1년 후 당뇨병 진행의 정량적 측정치: [206.11667725  68.07103297 176.88279035]


In [ ]:
print(diabetes.data)

          age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1  

In [ ]:
print(diabetes.target)

0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...  
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: target, Length: 442, dtype: float64


모델 평가

In [ ]:
from sklearn.model_selection import train_test_split

data_train, data_test, target_train, target_test = \
train_test_split(diabetes.data, diabetes.target, test_size=0.2, random_state=0)

In [ ]:
print('전체 데이터의 갯수 :',len(diabetes.data))
print('학습 데이터의 갯수 :',len(data_train))
print('테스트 데이터의 갯수 :',len(data_test))
print('테스트 데이터의 비율 :',len(target_test) / len(diabetes.data))

전체 데이터의 갯수 : 442
학습 데이터의 갯수 : 353
테스트 데이터의 갯수 : 89
테스트 데이터의 비율 : 0.20135746606334842


In [ ]:
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(diabetes.target[0:3],yPrediction)
rSquare = r2_score(diabetes.target[0:3],yPrediction)
print('표준평균오차 :',mse)
print('R 스퀘어 :',rSquare)

표준평균오차 : 1457.8111126596916
R 스퀘어 : -0.28228108033006505


In [2]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# 데이터 수집 및 전처리
diabetes = load_diabetes(as_frame=True)
data_train, data_test, target_train, target_test = \
train_test_split(diabetes.data, diabetes.target, test_size=0.2, random_state=0)

# 모델 훈련
model = LinearRegression()
model.fit(data_train,target_train)
print('회귀방정식의 계수 :',model.coef_)

# 모델 테스트
yPrediction = model.predict(data_test)

# 모델 평가
mse = mean_squared_error(target_test,yPrediction)
rSquare = r2_score(target_test,yPrediction)
print('표준평균오차 :',mse)
print('R 스퀘어 :',rSquare)

회귀방정식의 계수 : [ -35.55025079 -243.16508959  562.76234744  305.46348218 -662.70290089
  324.20738537   24.74879489  170.3249615   731.63743545   43.0309307 ]
표준평균오차 : 3424.2593342986925
R 스퀘어 : 0.3322332173106183


	로지스틱 회귀 알고리즘

데이터 수집 및 전처리

In [ ]:
from sklearn.datasets import load_iris

iris = load_iris(as_frame=True)
data_train, data_test, target_train, target_test = \
train_test_split(iris.data, iris.target, test_size=0.2, random_state=0)

In [ ]:
print(iris.data)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]


In [ ]:
print(iris.target)
print(iris.target[50:56])

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64
50    1
51    1
52    1
53    1
54    1
55    1
Name: target, dtype: int64


모델 훈련

In [11]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(data_train,target_train)
print('훈련된 회귀방정식의 계수 :',model.coef_)

훈련된 회귀방정식의 계수 : [[-0.39345168  0.8511139  -2.3601146  -1.01214086]
 [ 0.40917579 -0.31929939 -0.14621045 -0.78817065]
 [-0.01572411 -0.53181451  2.50632505  1.80031151]]


/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [12]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(data_train,target_train)
print('훈련된 회귀방정식의 계수 :',model.coef_)

훈련된 회귀방정식의 계수 : [[-0.39404717  0.84858916 -2.360915   -1.01267644]
 [ 0.41037412 -0.31739232 -0.14619146 -0.78742476]
 [-0.01632695 -0.53119684  2.50710646  1.8001012 ]]


모델 테스트

In [ ]:
yPrediction = model.predict(data_test)
print('회귀분석 모델로 예측한 붓꽃의 종류:', yPrediction)

회귀분석 모델로 예측한 붓꽃의 종류: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]


모델 평가

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(target_test, yPrediction)
print('로지스틱 선형 회귀 모델 정확도:', accuracy)

로지스틱 선형 회귀 모델 정확도: 1.0


In [13]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# 데이터 수집 및 전처리
iris = load_iris(as_frame=True)
data_train, data_test, target_train, target_test = \
train_test_split(iris.data, iris.target, test_size=0.2, random_state=0)

# 모델 훈련
model = LogisticRegression(max_iter=1000)
model.fit(data_train,target_train)

# 모델 테스트
yPrediction = model.predict(data_test)

# 모델 평가
accuracy = accuracy_score(target_test, yPrediction)
print('로지스틱 선형 회귀 모델 정확도:', accuracy)

로지스틱 선형 회귀 모델 정확도: 1.0
